#!/bin/sh
# generated by okay-deploy from demo-chat's Deployment value.
# Read it before you run it: it creates a user, installs units and starts them.
set -eu

command -v systemctl >/dev/null || { echo "this host has no systemd; okay-deploy's host target needs one" >&2; exit 3; }
command -v java >/dev/null || { echo "java is not installed. On Debian/Ubuntu: sudo apt-get install -y default-jre-headless" >&2; exit 3; }

id demo-chat >/dev/null 2>&1 || useradd --system --home /opt/demo-chat --shell /usr/sbin/nologin demo-chat
install -d -o demo-chat -g demo-chat /opt/demo-chat /var/lib/demo-chat /etc/demo-chat
install -d -o demo-chat -g demo-chat /opt/demo-chat/chat /var/lib/demo-chat/chat
# a Need.Volume names the path the SERVICE sees; with no container
# in the way, that path is a directory on this host and the install
# makes it, owned by the service's own user


for f in *.env; do
  [ -f "/etc/demo-chat/$f" ] || install -m 0600 -o root -g root "$f" "/etc/demo-chat/$f"
done
install -m 0644 *.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now chat.service

echo "installed. Settings are in /etc/demo-chat/, units in /etc/systemd/system/."
echo "Secrets are NOT installed: add their values to the env files, then: systemctl restart chat.service"
