#!/bin/sh
# generated by okay-deploy. Stops and removes the units; leaves
# /etc/demo-chat and /var/lib/demo-chat alone -- your settings and
# your data are not this script's to delete.
set -eu
systemctl disable --now chat.service || true
rm -f /etc/systemd/system/chat.service
systemctl daemon-reload
echo "removed. Settings in /etc/demo-chat and data in /var/lib/demo-chat were kept."
