package okay.foreign.golden

import okay.!
import okay.codec.Schema
import okay.foreign.{Condition, ForeignEval, ToPy, Ts}
import okay.foreign.TestTsOneShape.{Order, Totals}

// Generated by okay.foreign.TsFacade from the TypeScript module `facadets`: regenerate it, do not edit it.

final case class Receipt(lines: Vector[String], total: Double, note: Option[String]) derives Schema

object FacadeTs:

  /**
   * TypeScript: `total(order: Order): Totals`
   */
  def total(order: Order): Either[Condition, Totals] ! ForeignEval =
    Ts.fn[Totals]("facadets:total")(order)

  /**
   * TypeScript: `receipt(items: string[], each: number): Promise<Receipt>`
   */
  def receipt(items: Vector[String], each: Double): Either[Condition, Receipt] ! ForeignEval =
    Ts.fn[Receipt]("facadets:receipt")(items, each)

  /**
   * TypeScript: `greet(name: string, punct?: string): string`
   * Left out, being optional: punct.
   */
  def greet(name: String): Either[Condition, String] ! ForeignEval =
    Ts.fn[String]("facadets:greet")(name)

  /**
   * TypeScript: `echo(x: unknown): unknown`
   */
  def echo[Out: Schema, A1: ToPy](x: A1): Either[Condition, Out] ! ForeignEval =
    Ts.fn[Out]("facadets:echo")(x)

  // first: not generated — line 11: function first is generic; generics are not read

  // twice: not generated — line 12: a function type is not data

  // version: not generated — a 'const' export, not a function
