package okay.r

import okay.{!, given}
import okay.codec.Schema

/** one formal of an R function, as `okay_describe` reports it */
final case class RParam(name: String, default: Boolean) derives Schema

/** one function of an R module or package, as `okay_describe` reports it */
final case class RSig(name: String, params: Vector[RParam]) derives Schema

/**
 * An R module or package behind a GENERATED Scala object
 * (foreign-module-trait) — okay-py's `PyFacade` in R. R has no type
 * annotations, so every argument is a type parameter with `ToR` and every
 * answer one with `Schema`: the facade fixes the NAMES and the ARITY, and
 * the caller says the types. An R name that is not a Scala identifier
 * (`t.test`) is written with `_` for `.` and still calls the R name.
 *
 * {{{
 * sbt "okayR/runMain okay.r.RFacade stats Stats my.pkg"
 * }}}
 */
object RFacade:

  def describe(target: String): Either[Condition, Vector[RSig]] ! REval =
    R.fn[Vector[RSig]]("okay_describe")(target)

  private val keywords = Set("abstract", "case", "catch", "class", "def", "do", "else", "enum", "export",
    "extends", "false", "final", "finally", "for", "given", "if", "implicit", "import", "lazy", "match",
    "new", "null", "object", "override", "package", "private", "protected", "return", "sealed", "super",
    "then", "throw", "trait", "true", "try", "type", "val", "var", "while", "with", "yield")

  /** an R name as a Scala identifier, or None when it cannot be one */
  def ident(r: String): Option[String] =
    val s = r.replace('.', '_')
    if !s.matches("[A-Za-z_][A-Za-z0-9_]*") then None
    else if keywords(s) then Some(s"`$s`")
    else Some(s)

  def render(obj: String, pkg: String, target: String, sigs: Vector[RSig]): String =
    val b = StringBuilder()
    val callable = sigs.filter(s => ident(s.name).isDefined && s.params.count(!_.default) <= 4)
    val needsToR = callable.exists(_.params.exists(!_.default))
    b ++= s"package $pkg\n\n"
    b ++= "import okay.!\n"
    b ++= "import okay.codec.Schema\n"
    b ++= s"import okay.r.{${(Vector("Condition", "R", "REval") ++ Option.when(needsToR)("ToR")).mkString(", ")}}\n\n"
    b ++= s"/** Generated by okay.r.RFacade from `$target`: regenerate it, do not edit it. */\n"
    b ++= s"object $obj:\n"
    for s <- sigs do
      val required = s.params.filterNot(_.default)
      val defaulted = s.params.filter(_.default).map(_.name)
      b ++= "\n"
      ident(s.name) match
        case None => b ++= s"  // ${s.name}: not a Scala identifier; call it with R.fn(\"$target::${s.name}\")\n"
        case Some(_) if required.size > 4 =>
          b ++= s"  // ${s.name}: ${required.size} required formals; call it with R.fn(\"$target::${s.name}\") directly\n"
        case Some(name) =>
          b ++= "  /**\n"
          b ++= s"   * R: `${s.name}(${s.params.map(_.name).mkString(", ")})`\n"
          if defaulted.nonEmpty then b ++= s"   * Left out, having defaults: ${defaulted.mkString(", ")}.\n"
          b ++= "   */\n"
          val names = required.map(p => ident(p.name).getOrElse(s"arg${required.indexOf(p) + 1}"))
          val tps = "Out: Schema" +: required.indices.map(i => s"A${i + 1}: ToR")
          val params = names.zipWithIndex.map((n, i) => s"$n: A${i + 1}")
          b ++= s"  def $name${tps.mkString("[", ", ", "]")}(${params.mkString(", ")}): Either[Condition, Out] ! REval =\n"
          b ++= s"    R.fn[Out](\"$target::${s.name}\")(${names.mkString(", ")})\n"
    b.result()

  /** `target Object package [rscript]`: prints the source */
  def main(args: Array[String]): Unit = args.toList match
    case target :: obj :: pkg :: rest =>
      val r = RSubprocess.start(rest.headOption.getOrElse("Rscript"))
      try
        describe(target).runWith(using r.handler) match
          case Right(sigs) => print(render(obj, pkg, target, sigs))
          case Left(c) => System.err.println(s"${c.kind}: ${c.message}"); sys.exit(1)
      finally r.close()
    case _ =>
      System.err.println("usage: RFacade <package-or-module> <Object> <package> [rscript]")
      sys.exit(2)
