package okay2.codec

import scala.annotation.tailrec
import scala.collection.mutable

/**
 * The OTHER side's declaration of a value, from the same `Schema` the
 * codecs fold (okay-codec's Stubs, specs/schema-stubs.md): a Python
 * `TypedDict` module for what a Python worker receives, a TypeScript
 * `.d.ts` for what okay's JSON carries. The other language's checker
 * then sees the type okay checks at the boundary, and a renamed field
 * fails THERE, before a call.
 *
 * Each generator follows the codec that carries the value:
 *  - Python (okay-py's ValueCodec): a product is a dict, a sum is the
 *    case's dict plus `"type": Literal["Case"]`, `None` is None.
 *  - TypeScript (Json): a product is an object, a sum is
 *    `{ "Case": {...} }`, `None` is null, a `BigInt` a string of digits,
 *    bytes a base64 string.
 *
 * Declarations come out once each, in dependency order; a recursive type
 * refers to itself by name.
 */
object Stubs {

  // ---------------------------------------------------------------- Python

  private val pyKeywords = Set("False", "None", "True", "and", "as", "assert", "async", "await", "break",
    "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if",
    "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield")

  /** a Python module declaring every product and sum `schemas` reach */
  def python(schemas: Schema[_]*): String = {
    val w = new Writer
    schemas.foreach(s => pyType(s, w))
    val header =
      "# Generated by okay2.codec.Stubs from Scala Schemas: regenerate it, do not edit it.\n" +
        "# The shapes okay-py's ValueCodec sends: a case class is a dict, a sealed\n" +
        "# trait is its case's dict with a \"type\" naming the case.\n" +
        "from __future__ import annotations\n\n" +
        "from typing import Literal, Optional, TypedDict, Union"
    // PEP 8: two blank lines around every top-level declaration
    header + w.decls.map("\n\n\n" + _).mkString + "\n"
  }

  private def pyType(s: Schema[_], w: Writer): String = s match {
    case Schema.SInt | Schema.SLong | Schema.SBigInt => "int"
    case Schema.SDouble => "float"
    case Schema.SBool => "bool"
    case Schema.SString | Schema.SChar => "str"
    case Schema.SBytes => "bytes"
    case o: Schema.SOption[_] => s"Optional[${pyType(o.of(), w)}]"
    case l: Schema.SList[_] => s"list[${pyType(l.of(), w)}]"
    case v: Schema.SVector[_] => s"list[${pyType(v.of(), w)}]"
    case p: Schema.SProduct[_] => pyProduct(p, p.name, None, w)
    case su: Schema.SSum[_] => pySum(su, w)
    case i: Schema.SIso[_, _] => pyType(i.under(), w)
  }

  private def pyProduct(p: Schema.SProduct[_], name: String, tag: Option[String], w: Writer): String =
    w.declare(name) {
      val fields = tag.map(t => ("type", s"""Literal["$t"]""")).toVector ++
        p.fields.map { case (n, sc) => (n, pyType(sc(), w)) }
      if (fields.exists { case (n, _) => pyKeywords(n) || !n.matches("[A-Za-z_][A-Za-z0-9_]*") }) {
        // a field Python cannot spell as an attribute: the functional form
        val body = fields.map { case (n, t) => s""""$n": $t""" }.mkString(", ")
        s"""$name = TypedDict("$name", {$body})"""
      }
      else if (fields.isEmpty) s"class $name(TypedDict):\n    pass"
      else s"class $name(TypedDict):\n" + fields.map { case (n, t) => s"    $n: $t" }.mkString("\n")
    }

  private def pySum(su: Schema.SSum[_], w: Writer): String =
    w.declare(su.name) {
      val cases = su.cases.map { case (caseName, sc) =>
        val declared = w.freeName(caseName, su.name)
        sc() match {
          case p: Schema.SProduct[_] => pyProduct(p, declared, Some(caseName), w)
          case other =>
            val t = pyType(other, w)
            w.declare(declared)(s"class $declared(TypedDict):\n    type: Literal[\"$caseName\"]\n    value: $t")
        }
      }
      if (cases.size == 1) s"${su.name} = ${cases.head}"
      else s"${su.name} = Union[${cases.mkString(", ")}]"
    }

  // ------------------------------------------------------------ TypeScript

  /** a TypeScript declaration file for every product and sum `schemas` reach */
  def typescript(schemas: Schema[_]*): String = {
    val w = new Writer
    schemas.foreach(s => tsType(s, w))
    tsFile(w)
  }

  /**
   * The declarations for `root`, and an interface `<name>Paths` mapping
   * every key `JsonOptic.path` accepts against `root` to the TypeScript
   * type of what it focuses: a field is `"a.b"`, a list's element a
   * TEMPLATE-LITERAL key (`` [k: `tasks[${number}]`]: Task | null ``);
   * what might be absent is `| null`; a sum is also `"…$case"`; the root
   * is `""`; recursion is cut at `depth` segments.
   */
  def typescriptPaths(root: Schema[_], name: String, depth: Int = 6): String = {
    val w = new Writer
    val rootT = tsType(root, w)
    val keys = mutable.LinkedHashMap.empty[String, Vector[String]]
    def add(k: String, t: String): Unit = {
      val had = keys.getOrElse(k, Vector.empty)
      if (!had.contains(t)) keys.update(k, had :+ t)
    }
    def join(prefix: String, seg: String): String = if (prefix.isEmpty) seg else s"$prefix.$seg"
    def typed(s: Schema[_], nullable: Boolean): String = {
      val t = tsType(s, w)
      if (nullable && !t.endsWith("| null")) s"$t | null" else t
    }
    @tailrec def element(s: Schema[_]): Option[Schema[_]] = s match {
      case i: Schema.SIso[_, _] => element(i.under())
      case o: Schema.SOption[_] => element(o.of())
      case l: Schema.SList[_] => Some(l.of())
      case v: Schema.SVector[_] => Some(v.of())
      case _ => None
    }
    // an index is any number: TypeScript's own spelling of that key
    val anyIndex = "[" + "$" + "{number}]"
    def go(s: Schema[_], prefix: String, nullable: Boolean, left: Int): Unit = s match {
      case i: Schema.SIso[_, _] => go(i.under(), prefix, nullable, left)
      case o: Schema.SOption[_] => go(o.of(), prefix, true, left)
      case su: Schema.SSum[_] =>
        add(join(prefix, "$case"), typed(su, nullable))
        su.cases.foreach { case (_, cs) => go(cs(), prefix, true, left) }
      case p: Schema.SProduct[_] if left > 0 =>
        p.fields.foreach { case (n, fs) =>
          val f = fs()
          val key = join(prefix, n)
          add(key, typed(f, nullable))
          go(f, key, nullable, left - 1)
          element(f).foreach { item =>
            val at = key + anyIndex
            add(at, typed(item, true))
            go(item, at, true, left - 1)
          }
        }
      case _ => ()
    }
    add("", rootT)
    go(root, "", false, depth)
    val lines = keys.toVector.map { case (k, ts) =>
      val t = ts.mkString(" | ")
      if (k.contains(anyIndex)) s"  [k: `$k`]: $t;" else s"""  "$k": $t;"""
    }
    tsFile(w) +
      s"\n/** every key a live subscription to a $name may name, and what it is told (paths cut at depth $depth) */\n" +
      s"export interface ${name}Paths {\n${lines.mkString("\n")}\n}\n"
  }

  /**
   * The operations a TypeScript program may perform, as a record of
   * signatures (`export type ShopOps = { price_of: (a0: string) => number; ... }`),
   * with the declarations of every type they name. An operation given
   * without its Schemas is `(...args: any[]) => unknown`, and says so.
   */
  def typescriptOps(name: String, ops: Seq[(String, Option[(Schema[_], Schema[_])])]): String = {
    val w = new Writer
    val sigs = ops.map { case (op, types) =>
      types match {
        case Some((arg, res)) => s"  ${tsKey(op)}: (a0: ${tsType(arg, w)}) => ${tsType(res, w)};"
        case None => s"  ${tsKey(op)}: (...args: any[]) => unknown; // made without its Schemas"
      }
    }
    tsFile(w) +
      s"\n/** the operations a program may perform, each with what it answers */\nexport type $name = {\n${sigs.mkString("\n")}\n};\n"
  }

  private def tsFile(w: Writer): String = {
    val aliases = TsLeaves.filter { case (name, _, _) => w.leaves(name) }
      .map { case (name, t, note) => s"export type $name = $t;$note" }.mkString("\n")
    "// Generated by okay2.codec.Stubs from Scala Schemas: regenerate it, do not edit it.\n" +
      "// The shapes okay's JSON codec writes: a sum is { \"Case\": {...} }, None is null,\n" +
      "// a BigInt is a string of digits, bytes are a base64 string.\n" +
      (if (aliases.isEmpty) "" else "\n" + aliases + "\n") +
      w.decls.map("\n" + _ + "\n").mkString
  }

  /** the TypeScript type EXPRESSION for `s` (`Task`, `Task[]`, `Int | null`),
   * naming the declarations `typescript` writes for it */
  def typescriptType(s: Schema[_]): String = tsType(s, new Writer)

  /** the Scala leaves TypeScript would otherwise collapse, as NAMED
   * aliases, so `TsTypes` reading the declarations back recovers the
   * Scala type: Scala -> TypeScript -> Scala is exact. Emitted only when used. */
  private val TsLeaves = Vector(
    ("Int", "number", ""),
    ("Long", "number", " // exact as a JS number only to 2^53"),
    ("Char", "string", " // one character"),
    ("BigIntDigits", "string", " // a BigInt: its decimal digits"),
    ("Base64", "string", " // bytes, base64"))

  private def tsType(s: Schema[_], w: Writer): String = s match {
    case Schema.SInt => w.leaf("Int")
    case Schema.SLong => w.leaf("Long")
    case Schema.SDouble => "number"
    case Schema.SBool => "boolean"
    case Schema.SString => "string"
    case Schema.SChar => w.leaf("Char")
    case Schema.SBigInt => w.leaf("BigIntDigits")
    case Schema.SBytes => w.leaf("Base64")
    case o: Schema.SOption[_] => s"${tsType(o.of(), w)} | null"
    case l: Schema.SList[_] => tsArray(tsType(l.of(), w))
    case v: Schema.SVector[_] => tsArray(tsType(v.of(), w))
    case p: Schema.SProduct[_] => tsProduct(p, p.name, w)
    case su: Schema.SSum[_] => tsSum(su, w)
    case i: Schema.SIso[_, _] => tsType(i.under(), w)
  }

  private def tsArray(t: String): String = if (t.contains("|")) s"($t)[]" else s"$t[]"

  private def tsKey(n: String): String = if (n.matches("[A-Za-z_$][A-Za-z0-9_$]*")) n else s""""$n""""

  private def tsProduct(p: Schema.SProduct[_], name: String, w: Writer): String =
    w.declare(name) {
      val lines = p.fields.zipWithIndex.map { case ((n, sc), i) =>
        val s = sc()
        val optional = p.defaults.lift(i).flatten.isDefined
        s"  ${tsKey(n)}${if (optional) "?" else ""}: ${tsType(s, w)};"
      }
      if (lines.isEmpty) s"export interface $name {}"
      else s"export interface $name {\n${lines.mkString("\n")}\n}"
    }

  private def tsSum(su: Schema.SSum[_], w: Writer): String =
    w.declare(su.name) {
      val cases = su.cases.map { case (caseName, sc) =>
        val payload = sc() match {
          case p: Schema.SProduct[_] => tsProduct(p, w.freeName(caseName, su.name), w)
          case other => tsType(other, w)
        }
        s"  | { ${tsKey(caseName)}: $payload }"
      }
      s"export type ${su.name} =\n${cases.mkString("\n")};"
    }

  // ------------------------------------------------ TypeScript, on the wire

  /**
   * The `.d.ts` of what a TypeScript WORKER receives: the okay wire's
   * shapes, okay-py's — a sum carries `type: "Case"`, not the JSON codec's
   * `{ "Case": ... }`. A `Long` or `BigInt` is `number | bigint`. Bytes are
   * a `Uint8Array`.
   */
  def typescriptWire(schemas: Schema[_]*): String = {
    val w = new Writer
    schemas.foreach(s => wireType(s, w))
    "// Generated by okay2.codec.Stubs from Scala Schemas: regenerate it, do not edit it.\n" +
      "// The shapes the okay wire hands a TypeScript worker: a sealed trait\n" +
      "// is its case's object with a \"type\" naming the case; None is null.\n" +
      w.decls.map("\n" + _ + "\n").mkString
  }

  private def wireType(s: Schema[_], w: Writer): String = s match {
    case Schema.SInt | Schema.SDouble => "number"
    case Schema.SLong | Schema.SBigInt => "number | bigint"
    case Schema.SBool => "boolean"
    case Schema.SString | Schema.SChar => "string"
    case Schema.SBytes => "Uint8Array"
    case o: Schema.SOption[_] => s"${wireType(o.of(), w)} | null"
    case l: Schema.SList[_] => tsArray(wireType(l.of(), w))
    case v: Schema.SVector[_] => tsArray(wireType(v.of(), w))
    case p: Schema.SProduct[_] => wireProduct(p, p.name, None, w)
    case su: Schema.SSum[_] =>
      w.declare(su.name) {
        val cases = su.cases.map { case (caseName, sc) =>
          val declared = w.freeName(caseName, su.name)
          sc() match {
            case p: Schema.SProduct[_] => wireProduct(p, declared, Some(caseName), w)
            case other =>
              val t = wireType(other, w)
              w.declare(declared)(s"export interface $declared {\n  type: \"$caseName\";\n  value: $t;\n}")
          }
        }
        s"export type ${su.name} = ${cases.mkString(" | ")};"
      }
    case i: Schema.SIso[_, _] => wireType(i.under(), w)
  }

  private def wireProduct(p: Schema.SProduct[_], name: String, tag: Option[String], w: Writer): String =
    w.declare(name) {
      val lines = tag.map(t => s"""  type: "$t";""").toVector ++
        p.fields.map { case (n, sc) => s"  ${tsKey(n)}: ${wireType(sc(), w)};" }
      if (lines.isEmpty) s"export interface $name {}"
      else s"export interface $name {\n${lines.mkString("\n")}\n}"
    }

  // ----------------------------------------------------------------- shared

  /** the declarations made so far, in dependency order, each once */
  private final class Writer {
    val decls = mutable.ArrayBuffer.empty[String]
    private val started = mutable.Set.empty[String]
    /** the leaf aliases used, so only those are emitted */
    val leaves = mutable.Set.empty[String]
    def leaf(name: String): String = { leaves += name; name }

    /** declare `name` once: a name already started (a recursive
     * reference, or a second use) is answered by name */
    def declare(name: String)(body: => String): String = {
      if (!started(name)) {
        started += name
        val text = body
        decls += text
      }
      name
    }

    /** a case's own name, unless it is taken — then prefixed by its sum */
    def freeName(caseName: String, sumName: String): String =
      if (started(caseName)) s"$sumName$caseName" else caseName
  }
}
