package okay2.codec

import StubModels._

object TestTsTypes {
  /** golden/Golden.scala's text, which the test build COMPILES: what
   * TsTypes writes for StubModels' types */
  val golden: String = """package okay2.codec.golden

import okay2.codec.Schema

// Generated by okay2.codec.TsTypes from TypeScript declarations: regenerate it, do not edit it.

final case class Line(sku: String, qty: Int, price: Double)
object Line {
  implicit lazy val schema: Schema[Line] = Schema.derived
}

final case class Order(id: Long, lines: Vector[Line], note: Option[String], total: BigInt, raw: Array[Byte])
object Order {
  implicit lazy val schema: Schema[Order] = Schema.derived
}

sealed trait Shape
object Shape {
  final case class Circle(r: Double) extends Shape
  final case class Rect(w: Double, h: Double) extends Shape
  implicit lazy val schema: Schema[Shape] = Schema.derived
}

sealed trait Tree
object Tree {
  final case class Leaf(v: Int) extends Tree
  final case class Node(children: Vector[Tree]) extends Tree
  implicit lazy val schema: Schema[Tree] = Schema.derived
}
"""

  // no margin: the docs quote these lines
  val written: String = """
export interface User {
  id: number;
  name: string;
  email?: string;
  tags: string[];
}

export type Event = { Joined: Joined } | { Left: Left };

export interface Joined { user: User; at: string }
export interface Left { user: User }
"""
}

/** TypeScript declarations read into Scala 2 types (okay-codec's
 * TestTsTypes, typescript-types T3) */
class TestTsTypes extends munit.FunSuite {
  import TestTsTypes._

  private def declarations = Stubs.typescript(Order.schema, Shape.schema, Tree.schema)

  test("Scala -> TypeScript -> Scala: the golden Scala, which compiles") {
    assertEquals(TsTypes.scala(declarations, "okay2.codec.golden"), Right(golden))
  }

  test("...and back: the golden types' TypeScript IS the original TypeScript, byte for byte") {
    import okay2.codec.{golden => g}
    val again = Stubs.typescript(g.Order.schema, g.Shape.schema, g.Tree.schema)
    assertEquals(again, declarations)
  }

  test("types a TypeScript developer wrote: case classes and a sealed trait, an optional field as Option") {
    assertEquals(TsTypes.scala(written, "app"), Right("""package app

import okay2.codec.Schema

// Generated by okay2.codec.TsTypes from TypeScript declarations: regenerate it, do not edit it.

final case class User(id: Double, name: String, email: Option[String] = None, tags: Vector[String])
object User {
  implicit lazy val schema: Schema[User] = Schema.derived
}

sealed trait Event
object Event {
  final case class Joined(user: User, at: String) extends Event
  final case class Left(user: User) extends Event
  implicit lazy val schema: Schema[Event] = Schema.derived
}
"""))
  }

  test("the wire's shape of a sum (interfaces carrying type: \"Case\") reads as the same sealed trait") {
    val wire = Stubs.typescriptWire(Shape.schema)
    val got = TsTypes.scala(wire, "p")
    assert(got.exists(_.contains("sealed trait Shape\nobject Shape {\n  final case class Circle(r: Double) extends Shape\n  final case class Rect(w: Double, h: Double) extends Shape\n")), got.toString)
  }

  test("a plain alias is written in place: Scala 2 has no top-level type") {
    val got = TsTypes.scala("type Tags = string[];\ninterface Post { tags: Tags; also: Tags | null }", "p")
    assert(got.exists(_.contains("final case class Post(tags: Vector[String], also: Option[Vector[String]])")), got.toString)
    assert(got.exists(_.contains("// type Tags = Vector[String] (written in place)")), got.toString)
    assert(TsTypes.scala("type A = B;\ntype B = A;", "p").left.exists(_.contains("refers to itself")))
  }

  test("what is not data is refused by name and line, never guessed") {
    def refused(src: String) = TsTypes.scala(src, "p").left.getOrElse("")
    locally { val r = refused("interface Box<T> { v: T }"); assert(r.contains("generic"), r) }
    locally { val r = refused("type A = { a: string } & { b: string };"); assert(r.contains("intersection"), r) }
    locally { val r = refused("interface S {\n  on(x: number): void\n}"); assert(r.contains("line 2: field on is a method"), r) }
    locally { val r = refused("type Mode = \"on\" | \"off\";"); assert(r.contains("sum"), r) }
    locally { val r = refused("interface M { m: Record<string, number> }"); assert(r.contains("M.m: a map is not read"), r) }
    locally { val r = refused("export function f(): void {}"); assert(r.contains("only interfaces and type aliases describe data"), r) }
  }

  test("a module: its data, its functions, an unread export said so, and its imports") {
    val m = TsTypes.parseModule("import type { User, Group as G } from \"./model\";\nexport declare function find(id: number, all?: boolean): User | null;\nexport declare function each<T>(x: T): T;\nexport declare const version: string;\n")
    assert(m.isRight, m.toString)
    val mod = m.toOption.get
    assertEquals(mod.imported, Vector("User", "G"))
    assertEquals(mod.functions.collect { case Right(f) => (f.name, f.params.map(_.name)) }, Vector(("find", Vector("id", "all"))))
    assertEquals(mod.functions.collect { case Left(u) => u.name }, Vector("each", "version"))
  }
}
