#!/bin/sh
# generated by okay-deploy from okay-script's Deployment value.
# Read it before you run it: it creates a user, installs units and starts them.
set -eu

command -v systemctl >/dev/null || { echo "this host has no systemd; okay-deploy's host target needs one" >&2; exit 3; }
command -v java >/dev/null || { echo "java is not installed. On Debian/Ubuntu: sudo apt-get install -y default-jre-headless" >&2; exit 3; }

id okay-script >/dev/null 2>&1 || useradd --system --home /opt/okay-script --shell /usr/sbin/nologin okay-script
install -d -o okay-script -g okay-script /opt/okay-script /var/lib/okay-script /etc/okay-script
install -d -o okay-script -g okay-script /opt/okay-script/web /var/lib/okay-script/web
# a Need.Volume names the path the SERVICE sees; with no container
# in the way, that path is a directory on this host and the install
# makes it, owned by the service's own user
install -d -o okay-script -g okay-script /app/data

for f in *.env; do
  [ -f "/etc/okay-script/$f" ] || install -m 0600 -o root -g root "$f" "/etc/okay-script/$f"
done
install -m 0644 *.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now web.service

echo "installed. Settings are in /etc/okay-script/, units in /etc/systemd/system/."
echo "Secrets are NOT installed: add their values to the env files, then: systemctl restart web.service"
