#!/bin/sh
# generated by okay-deploy. Stops and removes the units; leaves
# /etc/okay-script and /var/lib/okay-script alone -- your settings and
# your data are not this script's to delete.
set -eu
systemctl disable --now web.service || true
rm -f /etc/systemd/system/web.service
systemctl daemon-reload
echo "removed. Settings in /etc/okay-script and data in /var/lib/okay-script were kept."
