package okay2.codec

import java.nio.file.Files
import StubModels._

/** The declarations written as a build step (okay-codec's TestStubFiles,
 * typescript-types T2) */
class TestStubFiles extends munit.FunSuite {

  test("written once, then left alone while the model does not change; rewritten when it does") {
    val dir = Files.createTempDirectory("okay-stub-files")
    val file = dir.resolve("frontend/src/model.ts")
    assert(StubFiles.typescript(file, Order.schema, Shape.schema), "the first write")
    val written = Files.readString(file)
    assert(written.startsWith("// Generated by okay2.codec.Stubs"), written)
    val at = Files.getLastModifiedTime(file)
    assert(!StubFiles.typescript(file, Order.schema, Shape.schema), "an unchanged model rewrote")
    assertEquals(Files.getLastModifiedTime(file), at)
    assert(StubFiles.typescript(file, Order.schema, Shape.schema, Tree.schema), "a new type")
    assert(Files.readString(file).contains("export type Tree ="))
  }

  test("the Python twin writes the TypedDict module") {
    val file = Files.createTempDirectory("okay-stub-files").resolve("model.py")
    assert(StubFiles.python(file, Order.schema))
    assert(Files.readString(file).contains("class Order(TypedDict):"))
  }
}
