package okay.py.golden

import okay.!
import okay.codec.Schema
import okay.py.{Condition, Py, PyEval, ToPy}

/** Generated by okay.py.PyFacade from the Python module `facadedemo`: regenerate it, do not edit it. */
object FacadeDemo:

  /**
   * Python: `echo(value)`
   */
  def echo[Out: Schema, A1: ToPy](value: A1): Either[Condition, Out] ! PyEval =
    Py.fn[Out]("facadedemo:echo")(value)

  /**
   * Python: `first(xs: list[int]) -> int | None`
   */
  def first(xs: Vector[Long]): Either[Condition, Option[Long]] ! PyEval =
    Py.fn[Option[Long]]("facadedemo:first")(xs)

  /**
   * A labelled number.
   * Python: `label(n: int, prefix: str) -> str`
   * Left out, having defaults: prefix.
   */
  def label(n: Long): Either[Condition, String] ! PyEval =
    Py.fn[String]("facadedemo:label")(n)

  /**
   * The arithmetic mean.
   * Python: `mean(xs: list[float]) -> float`
   */
  def mean(xs: Vector[Double]): Either[Condition, Double] ! PyEval =
    Py.fn[Double]("facadedemo:mean")(xs)
