package okay.codec

import TestStubs.*

/** typescript-types T2: the declarations written as a build step */
class TestStubFiles extends munit.FunSuite {

  test("written once, then left alone while the model does not change; rewritten when it does") {
    val dir = java.nio.file.Files.createTempDirectory("okay-stub-files")
    val file = dir.resolve("frontend/src/model.ts")
    assert(StubFiles.typescript(file, summon[Schema[Order]], summon[Schema[Shape]]), "the first write")
    val written = java.nio.file.Files.readString(file)
    assert(written.startsWith("// Generated by okay.codec.Stubs"), written)
    val at = java.nio.file.Files.getLastModifiedTime(file)
    assert(!StubFiles.typescript(file, summon[Schema[Order]], summon[Schema[Shape]]), "an unchanged model rewrote")
    assertEquals(java.nio.file.Files.getLastModifiedTime(file), at)
    assert(StubFiles.typescript(file, summon[Schema[Order]], summon[Schema[Shape]], summon[Schema[Tree]]), "a new type")
    assert(java.nio.file.Files.readString(file).contains("export type Tree ="))
  }

  test("the Python twin writes the TypedDict module") {
    val file = java.nio.file.Files.createTempDirectory("okay-stub-files").resolve("model.py")
    assert(StubFiles.python(file, summon[Schema[Order]]))
    assert(java.nio.file.Files.readString(file).contains("class Order(TypedDict):"))
  }
}
