package okay.mail

import okay.conf.{Secret, Secrets}
import okay.tls.{Tls, TlsConfig, SslMode}
import java.io.{BufferedReader, InputStreamReader, OutputStreamWriter, Writer}
import java.net.{InetAddress, ServerSocket, Socket}
import java.nio.charset.StandardCharsets.UTF_8

/**
 * STARTTLS, performed rather than decided (specs/mail.md).
 *
 * `TestSession` proves the client DECIDES to upgrade. Until this
 * suite there was nothing proving it CAN: `Tls.client` over the live
 * socket, the new reader and writer, the second EHLO — none of that
 * had ever run, and an unverified upgrade in a mail client is the
 * path where credentials travel in the clear if it silently does not
 * happen.
 *
 * Writing it needed the half of `okay-tls` that was missing:
 * `Tls.server` upgrades an already-accepted socket mid-protocol,
 * which is what any STARTTLS server does and what `serverSocket`
 * cannot be used for.
 *
 * The identity is generated by openssl into a temp directory, the way
 * `TestTls` does it; where openssl is absent the suite says so and
 * skips rather than passing quietly.
 */
object TestSmtpStartTls:
  lazy val dir = java.nio.file.Files.createTempDirectory("okay-mail-tls")
  lazy val generated: Boolean =
    try
      val cmd = Array("openssl", "req", "-x509", "-newkey", "rsa:2048",
        "-keyout", s"$dir/key.pem", "-out", s"$dir/cert.pem",
        "-days", "1", "-nodes", "-subj", "/CN=localhost",
        "-addext", "subjectAltName=DNS:localhost,IP:127.0.0.1")
      ProcessBuilder(cmd*).redirectErrorStream(true).start().waitFor() == 0
    catch case _: Exception => false

class TestSmtpStartTls extends munit.FunSuite {

  override def munitTests(): Seq[Test] = super.munitTests().map(_.tag(new munit.Tag("Live")))
  override def munitIgnore: Boolean = !TestSmtpStartTls.generated

  private def cert = s"${TestSmtpStartTls.dir}/cert.pem"
  private def key = Secret(s"file:${TestSmtpStartTls.dir}/key.pem")

  private val from = Address("noreply@example.com", Some("Example"))
  private val mail = Mail(from, Seq(Address("ada@example.org")),
    "Ваш код", "Ваш код: 123456")

  /**
   * A server that greets in the clear, offers STARTTLS, UPGRADES ITS
   * OWN SOCKET when asked, and then speaks the rest of SMTP inside
   * the tunnel. It records which lines arrived before the upgrade and
   * which after, because that distinction is the whole point.
   */
  private def serve(): (Int, () => (Vector[String], Vector[String]), () => Unit) =
    val server = new ServerSocket(0, 1, InetAddress.getLoopbackAddress)
    val clear = scala.collection.mutable.Buffer[String]()
    val secure = scala.collection.mutable.Buffer[String]()
    val thread = new Thread(() =>
      try
        var sock: Socket = server.accept()
        var in = new BufferedReader(new InputStreamReader(sock.getInputStream, UTF_8))
        var out: Writer = new OutputStreamWriter(sock.getOutputStream, UTF_8)
        def say(s: String): Unit = { out.write(s); out.write("\r\n"); out.flush() }
        var upgraded = false
        say("220 test ESMTP")
        var line = in.readLine()
        var inData = false
        while line != null do
          if upgraded then secure.synchronized { secure += line; () }
          else clear.synchronized { clear += line; () }
          if inData then
            if line == "." then { inData = false; say("250 2.0.0 queued as TLS1") }
          else if line.toUpperCase.startsWith("EHLO") then
            // AUTH is advertised ONLY after the upgrade, which is what
            // a real server does and what makes the second EHLO
            // necessary rather than decorative
            if upgraded then say("250-test\r\n250-AUTH PLAIN LOGIN\r\n250 SIZE 1000")
            else say("250-test\r\n250 STARTTLS")
          else if line.equalsIgnoreCase("STARTTLS") then
            say("220 go ahead")
            Tls.server(sock, cert, key, Secrets.file) match
              case Left(why) => say(s"454 $why")
              case Right(s2) =>
                sock = s2
                in = new BufferedReader(new InputStreamReader(sock.getInputStream, UTF_8))
                out = new OutputStreamWriter(sock.getOutputStream, UTF_8)
                upgraded = true
          else if line.toUpperCase.startsWith("AUTH") then say("235 2.7.0 authenticated")
          else if line.toUpperCase.startsWith("MAIL FROM") then say("250 ok")
          else if line.toUpperCase.startsWith("RCPT TO") then say("250 ok")
          else if line.equalsIgnoreCase("DATA") then { inData = true; say("354 go ahead") }
          else if line.equalsIgnoreCase("QUIT") then { say("221 bye"); line = null }
          else say("250 ok")
          if line != null then line = in.readLine()
        sock.close()
      catch case _: Throwable => ()
      finally try server.close() catch case _: Throwable => ())
    thread.setDaemon(true)
    thread.start()
    (server.getLocalPort,
      () => (clear.synchronized(clear.toVector), secure.synchronized(secure.toVector)),
      () => try server.close() catch case _: Throwable => ())

  test("the upgrade happens, and everything that matters is inside it") {
    val (port, heard, stop) = serve()
    try
      // VerifyCa rather than VerifyFull: the certificate names
      // localhost and the socket is opened on 127.0.0.1, and the
      // hostname check is okay-tls's own test's business rather than
      // this one's
      val server = Smtp.Server("127.0.0.1", port, from,
        tls = TlsConfig(mode = SslMode.VerifyCa, caFile = Some(cert)))
      val result = Smtp.blocking(server, Secrets.file, mail)
      assert(result.isRight, result.toString)

      val (clear, secure) = heard()
      // in the clear: exactly the greeting exchange and the request
      assertEquals(clear.map(_.takeWhile(_ != ' ')), Vector("EHLO", "STARTTLS"))
      // and everything a person would mind is on the other side
      assert(secure.exists(_.startsWith("MAIL FROM:")), secure.toString)
      assert(secure.exists(_.startsWith("RCPT TO:")), secure.toString)
      assert(secure.contains("DATA"), secure.toString)
      assert(secure.exists(_.startsWith("Subject: =?UTF-8?B?")), secure.toString)
      assert(clear.forall(l => !l.startsWith("MAIL FROM")),
        "the envelope must not appear before the upgrade")
    finally stop()
  }

  test("credentials go AFTER the upgrade and never before it") {
    val (port, heard, stop) = serve()
    try
      val server = Smtp.Server("127.0.0.1", port, from,
        login = Some(Session.Login("noreply", "hunter2")),
        tls = TlsConfig(mode = SslMode.VerifyCa, caFile = Some(cert)))
      Smtp.blocking(server, Secrets.file, mail): Unit
      val (clear, secure) = heard()
      assert(clear.forall(l => !l.toUpperCase.startsWith("AUTH")),
        s"an AUTH line before the upgrade is the defect this test exists for: $clear")
      // the server above advertises AUTH only after the upgrade, and
      // the client re-read the capabilities to find it
      assert(secure.exists(_.toUpperCase.startsWith("AUTH PLAIN ")),
        s"the credentials should travel inside the tunnel: $secure")
      assert(secure.exists(_.startsWith("MAIL FROM:")),
        s"and the conversation should continue after them: $secure")
    finally stop()
  }

  test("a certificate the client will not trust refuses the send, and says so") {
    val (port, _, stop) = serve()
    try
      // VerifyFull against a self-signed certificate with no CA given:
      // the handshake must refuse, and the caller must get a value
      val server = Smtp.Server("127.0.0.1", port, from,
        tls = TlsConfig(mode = SslMode.VerifyFull))
      Smtp.blocking(server, Secrets.file, mail) match
        case Left(Mail.Rejection.Connection(why)) => assert(why.contains("STARTTLS"), why)
        case other => fail(s"an untrusted server must not receive the message: $other")
    finally stop()
  }
}
