#!/bin/sh
# generated by okay-deploy from okay-script's Deployment value
#
# The chart REFERENCES this Secret and does not own it, on purpose:
# a templated Secret would be overwritten with blanks by the next
# `helm upgrade`, and the first symptom is every pod crash-looping
# at 3am. So it is created once, here, by you.
#
# No value is in this file, and none ever will be — fill them in
# where you run it, from your own vault.
set -e
RELEASE=${RELEASE:-okay-script}
NAMESPACE=${NAMESPACE:-default}

# this deployment reads no secrets; nothing to create.
