package okay.codec

import TestStubs.*

object TestTsTypes:
  /** the golden file's text: what TsTypes writes for TestStubs' types, which
   * `golden/Golden.scala` holds and the test build COMPILES */
  val golden: String = """package okay.codec.golden

import okay.codec.Schema

// Generated by okay.codec.TsTypes from TypeScript declarations: regenerate it, do not edit it.

final case class Line(sku: String, qty: Int, price: Double) derives Schema

final case class Order(id: Long, lines: Vector[Line], note: Option[String], total: BigInt, raw: Array[Byte]) derives Schema

enum Shape derives Schema:
  case Circle(r: Double)
  case Rect(w: Double, h: Double)

enum Tree derives Schema:
  case Leaf(v: Int)
  case Node(children: Vector[Tree])
"""

  // no margin: the docs quote these lines
  val written: String = """
export interface User {
  id: number;
  name: string;
  email?: string;
  tags: string[];
}

export type Event = { Joined: Joined } | { Left: Left };

export interface Joined { user: User; at: string }
export interface Left { user: User }
"""

/** typescript-types T3: TypeScript declarations read into Scala types */
class TestTsTypes extends munit.FunSuite {
  import TestTsTypes.*

  private def declarations = Stubs.typescript(summon[Schema[Order]], summon[Schema[Shape]], summon[Schema[Tree]])

  test("Scala -> TypeScript -> Scala: the golden Scala, which compiles") {
    assertEquals(TsTypes.scala(declarations, "okay.codec.golden"), Right(golden))
  }

  test("...and back: the golden types' TypeScript IS the original TypeScript, byte for byte") {
    import okay.codec.golden as g
    val again = Stubs.typescript(summon[Schema[g.Order]], summon[Schema[g.Shape]], summon[Schema[g.Tree]])
    assertEquals(again, declarations)
  }

  test("types a TypeScript developer wrote: case classes and an enum, an optional field as Option") {
    assertEquals(TsTypes.scala(written, "app"), Right("""package app

import okay.codec.Schema

// Generated by okay.codec.TsTypes from TypeScript declarations: regenerate it, do not edit it.

final case class User(id: Double, name: String, email: Option[String] = None, tags: Vector[String]) derives Schema

enum Event derives Schema:
  case Joined(user: User, at: String)
  case Left(user: User)
"""))
  }

  test("the wire's shape of a sum (interfaces carrying type: \"Case\") reads as the same enum") {
    val wire = Stubs.typescriptWire(summon[Schema[Shape]])
    assert(TsTypes.scala(wire, "p").exists(_.contains("enum Shape derives Schema:\n  case Circle(r: Double)\n  case Rect(w: Double, h: Double)")),
      TsTypes.scala(wire, "p").toString)
  }

  test("what is not data is refused by name and line, never guessed") {
    def refused(src: String) = TsTypes.scala(src, "p").left.getOrElse("")
    { val r = refused("interface Box<T> { v: T }"); assert(r.contains("generic"), r) }
    { val r = refused("type A = { a: string } & { b: string };"); assert(r.contains("intersection"), r) }
    { val r = refused("interface S {\n  on(x: number): void\n}"); assert(r.contains("line 2: field on is a method"), r) }
    { val r = refused("type Mode = \"on\" | \"off\";"); assert(r.contains("sum"), r) }
    { val r = refused("interface M { m: Record<string, number> }"); assert(r.contains("M.m: a map is not read"), r) }
    { val r = refused("export function f(): void {}"); assert(r.contains("only interfaces and type aliases describe data"), r) }
  }
}
