#!/bin/sh
# generated by okay-deploy from okay-script's Deployment value
#
# Everything railway.json cannot say: the project, the services,
# the managed engines and the variables. Run this ONCE.
# No secret value is in this file and none ever will be.
set -e
railway init --name 'okay-script' || echo 'project exists; `railway link` it instead'

# ---- web
railway add --service 'web'
railway variables --service 'web' \
  --set 'OKAY_PAGES=/app/pages' \
  --set 'OKAY_PORT=8080' \
  --set 'OKAY_OPS=1' \
  --set 'PORT=8080' \
  --skip-deploys
# railway volumes are made in the dashboard: Service -> Settings -> Volumes
#   web: mount /app/data (1Gi)
