package okay.codec

import scala.collection.mutable

/**
 * The OTHER side's declaration of a value, from the same `Schema` the
 * codecs fold (schema-stubs, specs/schema-stubs.md): a Python `TypedDict`
 * module for what okay-py sends, a TypeScript `.d.ts` for what okay's JSON
 * carries. The other language's type checker then sees the type okay
 * checks at the boundary, and a renamed field fails THERE, before a call.
 *
 * Each generator follows the codec that carries the value — a declaration
 * is only true if it matches the wire:
 *  - Python (okay-py's PyCodec): a product is a dict, a sum is the case's
 *    dict plus `"type": Literal["Case"]`, `None` is None, a `BigInt` an int.
 *  - TypeScript (okay-codec's Json): a product is an object, a sum is
 *    `{ "Case": {...} }`, `None` is null, a `BigInt` a string of digits,
 *    bytes a base64 string.
 *
 * Declarations come out once each, in dependency order; a recursive type
 * refers to itself by name (Python's `from __future__ import annotations`
 * and TypeScript both allow the forward reference).
 */
object Stubs:

  // ---------------------------------------------------------------- Python

  private val pyKeywords = Set("False", "None", "True", "and", "as", "assert", "async", "await", "break",
    "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if",
    "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield")

  /** a Python module declaring every product and sum `schemas` reach */
  def python(schemas: Schema[?]*): String =
    val w = Writer()
    schemas.foreach(s => pyType(s, w))
    val header =
      "# Generated by okay.codec.Stubs from Scala Schemas: regenerate it, do not edit it.\n" +
        "# The shapes okay-py's PyCodec sends: a case class is a dict, a sealed\n" +
        "# trait or enum is its case's dict with a \"type\" naming the case.\n" +
        "from __future__ import annotations\n\n" +
        "from typing import Literal, Optional, TypedDict, Union"
    // PEP 8: two blank lines around every top-level declaration
    header + w.decls.map("\n\n\n" + _).mkString + "\n"

  private def pyType(s: Schema[?], w: Writer): String = s match
    case Schema.SInt | Schema.SLong | Schema.SBigInt => "int"
    case Schema.SDouble => "float"
    case Schema.SBool => "bool"
    case Schema.SString | Schema.SChar => "str"
    case Schema.SBytes => "bytes"
    case o: Schema.SOption[?] => s"Optional[${pyType(o.of(), w)}]"
    case l: Schema.SList[?] => s"list[${pyType(l.of(), w)}]"
    case v: Schema.SVector[?] => s"list[${pyType(v.of(), w)}]"
    case p: Schema.SProduct[?] => pyProduct(p, p.name, None, w)
    case su: Schema.SSum[?] => pySum(su, w)
    case i: Schema.SIso[?, ?] => pyType(i.under(), w)

  private def pyProduct(p: Schema.SProduct[?], name: String, tag: Option[String], w: Writer): String =
    w.declare(name) {
      val fields = tag.map(t => ("type", s"Literal[\"$t\"]")).toVector ++
        p.fields.map((n, sc) => (n, pyType(sc(), w)))
      if fields.exists((n, _) => pyKeywords(n) || !n.matches("[A-Za-z_][A-Za-z0-9_]*")) then
        // a field Python cannot spell as an attribute: the functional form
        val body = fields.map((n, t) => s"\"$n\": $t").mkString(", ")
        s"$name = TypedDict(\"$name\", {$body})"
      else if fields.isEmpty then s"class $name(TypedDict):\n    pass"
      else s"class $name(TypedDict):\n" + fields.map((n, t) => s"    $n: $t").mkString("\n")
    }

  private def pySum(su: Schema.SSum[?], w: Writer): String =
    w.declare(su.name) {
      val cases = su.cases.map { (caseName, sc) =>
        val declared = w.freeName(caseName, su.name)
        sc() match
          case p: Schema.SProduct[?] => pyProduct(p, declared, Some(caseName), w)
          case other =>
            val t = pyType(other, w)
            w.declare(declared)(s"class $declared(TypedDict):\n    type: Literal[\"$caseName\"]\n    value: $t")
      }
      if cases.size == 1 then s"${su.name} = ${cases.head}"
      else s"${su.name} = Union[${cases.mkString(", ")}]"
    }

  // ------------------------------------------------------------ TypeScript

  /** a TypeScript declaration file for every product and sum `schemas` reach */
  def typescript(schemas: Schema[?]*): String =
    val w = Writer()
    schemas.foreach(s => tsType(s, w))
    "// Generated by okay.codec.Stubs from Scala Schemas: regenerate it, do not edit it.\n" +
      "// The shapes okay's JSON codec writes: a sum is { \"Case\": {...} }, None is null,\n" +
      "// a BigInt is a string of digits, bytes are a base64 string.\n" +
      w.decls.map("\n" + _ + "\n").mkString

  private def tsType(s: Schema[?], w: Writer): String = s match
    case Schema.SInt | Schema.SLong | Schema.SDouble => "number"
    case Schema.SBool => "boolean"
    case Schema.SString | Schema.SChar | Schema.SBytes | Schema.SBigInt => "string"
    case o: Schema.SOption[?] => s"${tsType(o.of(), w)} | null"
    case l: Schema.SList[?] => tsArray(tsType(l.of(), w))
    case v: Schema.SVector[?] => tsArray(tsType(v.of(), w))
    case p: Schema.SProduct[?] => tsProduct(p, p.name, w)
    case su: Schema.SSum[?] => tsSum(su, w)
    case i: Schema.SIso[?, ?] => tsType(i.under(), w)

  private def tsArray(t: String): String = if t.contains("|") then s"($t)[]" else s"$t[]"

  private def tsKey(n: String): String = if n.matches("[A-Za-z_$][A-Za-z0-9_$]*") then n else s"\"$n\""

  private def tsProduct(p: Schema.SProduct[?], name: String, w: Writer): String =
    w.declare(name) {
      val lines = p.fields.zipWithIndex.map { case ((n, sc), i) =>
        val s = sc()
        val optional = p.defaults.lift(i).flatten.isDefined
        val note = s match
          case Schema.SLong => " // a Long: exact as a JS number only to 2^53"
          case _ => ""
        s"  ${tsKey(n)}${if optional then "?" else ""}: ${tsType(s, w)};$note"
      }
      if lines.isEmpty then s"export interface $name {}"
      else s"export interface $name {\n${lines.mkString("\n")}\n}"
    }

  private def tsSum(su: Schema.SSum[?], w: Writer): String =
    w.declare(su.name) {
      val cases = su.cases.map { (caseName, sc) =>
        val payload = sc() match
          case p: Schema.SProduct[?] => tsProduct(p, w.freeName(caseName, su.name), w)
          case other => tsType(other, w)
        s"  | { ${tsKey(caseName)}: $payload }"
      }
      s"export type ${su.name} =\n${cases.mkString("\n")};"
    }

  // ----------------------------------------------------------------- shared

  /** the declarations made so far, in dependency order, each once */
  private final class Writer:
    val decls = mutable.ArrayBuffer.empty[String]
    private val started = mutable.Set.empty[String]

    /** declare `name` once: a name already started (a recursive
     * reference, or a second use) is answered by name */
    def declare(name: String)(body: => String): String =
      if !started(name) then
        started += name
        val text = body
        decls += text
      name

    /** a case's own name, unless it is taken — then prefixed by its sum */
    def freeName(caseName: String, sumName: String): String =
      if started(caseName) then s"$sumName$caseName" else caseName
