package okay.codec

import scala.collection.mutable

/**
 * The OTHER side's declaration of a value, from the same `Schema` the
 * codecs fold (schema-stubs, specs/schema-stubs.md): a Python `TypedDict`
 * module for what okay-py sends, a TypeScript `.d.ts` for what okay's JSON
 * carries. The other language's type checker then sees the type okay
 * checks at the boundary, and a renamed field fails THERE, before a call.
 *
 * Each generator follows the codec that carries the value — a declaration
 * is only true if it matches the wire:
 *  - Python (okay-py's PyCodec): a product is a dict, a sum is the case's
 *    dict plus `"type": Literal["Case"]`, `None` is None, a `BigInt` an int.
 *  - TypeScript (okay-codec's Json): a product is an object, a sum is
 *    `{ "Case": {...} }`, `None` is null, a `BigInt` a string of digits,
 *    bytes a base64 string.
 *
 * Declarations come out once each, in dependency order; a recursive type
 * refers to itself by name (Python's `from __future__ import annotations`
 * and TypeScript both allow the forward reference).
 */
object Stubs:

  // ---------------------------------------------------------------- Python

  private val pyKeywords = Set("False", "None", "True", "and", "as", "assert", "async", "await", "break",
    "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if",
    "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield")

  /** a Python module declaring every product and sum `schemas` reach */
  def python(schemas: Schema[?]*): String =
    val w = Writer()
    schemas.foreach(s => pyType(s, w))
    val header =
      "# Generated by okay.codec.Stubs from Scala Schemas: regenerate it, do not edit it.\n" +
        "# The shapes okay-py's PyCodec sends: a case class is a dict, a sealed\n" +
        "# trait or enum is its case's dict with a \"type\" naming the case.\n" +
        "from __future__ import annotations\n\n" +
        "from typing import Literal, Optional, TypedDict, Union"
    // PEP 8: two blank lines around every top-level declaration
    header + w.decls.map("\n\n\n" + _).mkString + "\n"

  private def pyType(s: Schema[?], w: Writer): String = s match
    case Schema.SInt | Schema.SLong | Schema.SBigInt => "int"
    case Schema.SDouble => "float"
    case Schema.SBool => "bool"
    case Schema.SString | Schema.SChar => "str"
    case Schema.SBytes => "bytes"
    case o: Schema.SOption[?] => s"Optional[${pyType(o.of(), w)}]"
    case l: Schema.SList[?] => s"list[${pyType(l.of(), w)}]"
    case v: Schema.SVector[?] => s"list[${pyType(v.of(), w)}]"
    case p: Schema.SProduct[?] => pyProduct(p, p.name, None, w)
    case su: Schema.SSum[?] => pySum(su, w)
    case i: Schema.SIso[?, ?] => pyType(i.under(), w)

  private def pyProduct(p: Schema.SProduct[?], name: String, tag: Option[String], w: Writer): String =
    w.declare(name) {
      val fields = tag.map(t => ("type", s"Literal[\"$t\"]")).toVector ++
        p.fields.map((n, sc) => (n, pyType(sc(), w)))
      if fields.exists((n, _) => pyKeywords(n) || !n.matches("[A-Za-z_][A-Za-z0-9_]*")) then
        // a field Python cannot spell as an attribute: the functional form
        val body = fields.map((n, t) => s"\"$n\": $t").mkString(", ")
        s"$name = TypedDict(\"$name\", {$body})"
      else if fields.isEmpty then s"class $name(TypedDict):\n    pass"
      else s"class $name(TypedDict):\n" + fields.map((n, t) => s"    $n: $t").mkString("\n")
    }

  private def pySum(su: Schema.SSum[?], w: Writer): String =
    w.declare(su.name) {
      val cases = su.cases.map { (caseName, sc) =>
        val declared = w.freeName(caseName, su.name)
        sc() match
          case p: Schema.SProduct[?] => pyProduct(p, declared, Some(caseName), w)
          case other =>
            val t = pyType(other, w)
            w.declare(declared)(s"class $declared(TypedDict):\n    type: Literal[\"$caseName\"]\n    value: $t")
      }
      if cases.size == 1 then s"${su.name} = ${cases.head}"
      else s"${su.name} = Union[${cases.mkString(", ")}]"
    }

  // ------------------------------------------------------------ TypeScript

  /** a TypeScript declaration file for every product and sum `schemas` reach */
  def typescript(schemas: Schema[?]*): String =
    val w = Writer()
    schemas.foreach(s => tsType(s, w))
    val aliases = TsLeaves.filter((name, _, _) => w.leaves(name))
      .map((name, t, note) => s"export type $name = $t;$note").mkString("\n")
    "// Generated by okay.codec.Stubs from Scala Schemas: regenerate it, do not edit it.\n" +
      "// The shapes okay's JSON codec writes: a sum is { \"Case\": {...} }, None is null,\n" +
      "// a BigInt is a string of digits, bytes are a base64 string.\n" +
      (if aliases.isEmpty then "" else "\n" + aliases + "\n") +
      w.decls.map("\n" + _ + "\n").mkString

  /**
   * The Scala leaves TypeScript would otherwise collapse, as NAMED aliases
   * (typescript-types T3): TypeScript sees exactly `number`/`string`, and
   * `TsTypes` reading the declarations back recovers the Scala type, so
   * Scala -> TypeScript -> Scala is exact. Emitted only when used.
   */
  private val TsLeaves = Vector(
    ("Int", "number", ""),
    ("Long", "number", " // exact as a JS number only to 2^53"),
    ("Char", "string", " // one character"),
    ("BigIntDigits", "string", " // a BigInt: its decimal digits"),
    ("Base64", "string", " // bytes, base64"))

  private def tsType(s: Schema[?], w: Writer): String = s match
    case Schema.SInt => w.leaf("Int")
    case Schema.SLong => w.leaf("Long")
    case Schema.SDouble => "number"
    case Schema.SBool => "boolean"
    case Schema.SString => "string"
    case Schema.SChar => w.leaf("Char")
    case Schema.SBigInt => w.leaf("BigIntDigits")
    case Schema.SBytes => w.leaf("Base64")
    case o: Schema.SOption[?] => s"${tsType(o.of(), w)} | null"
    case l: Schema.SList[?] => tsArray(tsType(l.of(), w))
    case v: Schema.SVector[?] => tsArray(tsType(v.of(), w))
    case p: Schema.SProduct[?] => tsProduct(p, p.name, w)
    case su: Schema.SSum[?] => tsSum(su, w)
    case i: Schema.SIso[?, ?] => tsType(i.under(), w)

  private def tsArray(t: String): String = if t.contains("|") then s"($t)[]" else s"$t[]"

  private def tsKey(n: String): String = if n.matches("[A-Za-z_$][A-Za-z0-9_$]*") then n else s"\"$n\""

  private def tsProduct(p: Schema.SProduct[?], name: String, w: Writer): String =
    w.declare(name) {
      val lines = p.fields.zipWithIndex.map { case ((n, sc), i) =>
        val s = sc()
        val optional = p.defaults.lift(i).flatten.isDefined
        s"  ${tsKey(n)}${if optional then "?" else ""}: ${tsType(s, w)};"
      }
      if lines.isEmpty then s"export interface $name {}"
      else s"export interface $name {\n${lines.mkString("\n")}\n}"
    }

  private def tsSum(su: Schema.SSum[?], w: Writer): String =
    w.declare(su.name) {
      val cases = su.cases.map { (caseName, sc) =>
        val payload = sc() match
          case p: Schema.SProduct[?] => tsProduct(p, w.freeName(caseName, su.name), w)
          case other => tsType(other, w)
        s"  | { ${tsKey(caseName)}: $payload }"
      }
      s"export type ${su.name} =\n${cases.mkString("\n")};"
    }

  // ------------------------------------------------ TypeScript, on the wire

  /**
   * The `.d.ts` of what a TypeScript WORKER receives (specs/typescript.md):
   * the okay wire's shapes, which are okay-py's (PyCodec) — a sum carries
   * `type: "Case"`, as in Python, not the JSON codec's `{ "Case": ... }`.
   * A `Long` or `BigInt` is `number | bigint`: an integer past 2^53 arrives
   * as a `bigint`, a smaller one as a `number`. Bytes are a `Uint8Array`.
   */
  def typescriptWire(schemas: Schema[?]*): String =
    val w = Writer()
    schemas.foreach(s => wireType(s, w))
    "// Generated by okay.codec.Stubs from Scala Schemas: regenerate it, do not edit it.\n" +
      "// The shapes the okay wire hands a TypeScript worker: a sealed trait or enum\n" +
      "// is its case's object with a \"type\" naming the case; None is null.\n" +
      w.decls.map("\n" + _ + "\n").mkString

  private def wireType(s: Schema[?], w: Writer): String = s match
    case Schema.SInt | Schema.SDouble => "number"
    case Schema.SLong | Schema.SBigInt => "number | bigint"
    case Schema.SBool => "boolean"
    case Schema.SString | Schema.SChar => "string"
    case Schema.SBytes => "Uint8Array"
    case o: Schema.SOption[?] => s"${wireType(o.of(), w)} | null"
    case l: Schema.SList[?] => tsArray(wireType(l.of(), w))
    case v: Schema.SVector[?] => tsArray(wireType(v.of(), w))
    case p: Schema.SProduct[?] => wireProduct(p, p.name, None, w)
    case su: Schema.SSum[?] =>
      w.declare(su.name) {
        val cases = su.cases.map { (caseName, sc) =>
          val declared = w.freeName(caseName, su.name)
          sc() match
            case p: Schema.SProduct[?] => wireProduct(p, declared, Some(caseName), w)
            case other =>
              val t = wireType(other, w)
              w.declare(declared)(s"export interface $declared {\n  type: \"$caseName\";\n  value: $t;\n}")
        }
        s"export type ${su.name} = ${cases.mkString(" | ")};"
      }
    case i: Schema.SIso[?, ?] => wireType(i.under(), w)

  private def wireProduct(p: Schema.SProduct[?], name: String, tag: Option[String], w: Writer): String =
    w.declare(name) {
      val lines = tag.map(t => s"  type: \"$t\";").toVector ++
        p.fields.map((n, sc) => s"  ${tsKey(n)}: ${wireType(sc(), w)};")
      if lines.isEmpty then s"export interface $name {}"
      else s"export interface $name {\n${lines.mkString("\n")}\n}"
    }

  // ----------------------------------------------------------------- shared

  /** the declarations made so far, in dependency order, each once */
  private final class Writer:
    val decls = mutable.ArrayBuffer.empty[String]
    private val started = mutable.Set.empty[String]
    /** the leaf aliases used, so only those are emitted */
    val leaves = mutable.Set.empty[String]
    def leaf(name: String): String = { leaves += name; name }

    /** declare `name` once: a name already started (a recursive
     * reference, or a second use) is answered by name */
    def declare(name: String)(body: => String): String =
      if !started(name) then
        started += name
        val text = body
        decls += text
      name

    /** a case's own name, unless it is taken — then prefixed by its sum */
    def freeName(caseName: String, sumName: String): String =
      if started(caseName) then s"$sumName$caseName" else caseName
