package okay.intent

import java.nio.file.{Files, Paths}

/**
 * Regenerates the shipped model (specs/intent-classify.md).
 *
 *   sbt "okayIntentJVM/Test/runMain okay.intent.MakeModel"
 *
 * The artifact in `Models` is a generated Scala source rather than a
 * resource on purpose: `okay-intent` is cross-built, and a classpath
 * resource is a JVM-only way to load a model into a module whose whole
 * point is that it needs nothing at runtime.
 *
 * It lives in the TEST scope because generating it needs the fixture,
 * and the fixture is a test. Nothing on the main path fits anything.
 */
object MakeModel {

  /** the corpus the shipped model is fitted on: the English half of
   * the labelled fixture. Not the parallel set — see the Results:
   * fifteen held-out rows per language cannot support a claim, and a
   * multilingual fit costs English three points to buy numbers I would
   * not stand behind. */
  def corpus: Seq[(String, String)] =
    IntentFixture.labelled.zipWithIndex.filter(_._2 % 2 == 1).map(_._1)

  def model: CharGrams.Trained = Fit.grams(corpus)

  /** a Scala string literal holding exactly this text */
  private def quoted(s: String): String =
    "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  /** a class file holds a string constant of at most 65535 UTF-8
   * bytes, and the (2,3) @4096 artifact is 171KB — so the JSON is
   * emitted as literals of at most `chunk` characters (the text is
   * ASCII: base64 cells and JSON punctuation) and joined once at load */
  private val chunk = 60000

  def source: String =
    val json = Fit.save(model)
    val parts = json.grouped(chunk).map(quoted).toVector
    val lits = parts.mkString(",\n      ")
    s"""package okay.intent
       |
       |/**
       | * GENERATED by `okay.intent.MakeModel` — do not edit by hand.
       | *
       | * The shipped meeting classifier, as data, in ${parts.length} pieces
       | * because a class file caps one string constant at 64KB. See
       | * `Models` for what it is, what it scores, and what it is not.
       | */
       |private[intent] object MeetingModel:
       |  val json: String =
       |    Vector(
       |      $lits
       |    ).mkString
       |""".stripMargin

  /** the rows the candidate is judged on: the half it was NOT fitted
   * on, which is the same half every published number here uses */
  def heldOut: Seq[(String, String)] =
    IntentFixture.labelled.zipWithIndex.filter(_._2 % 2 == 0).map(_._1)

  /**
   * Refitting goes through the GATE (intent-refit-gate): fit, score
   * against the artifact already in the tree, and write only if no
   * class falls below the law or slides against the incumbent. A
   * refit that raises the headline while killing a class is the
   * failure this path is guarded for, and it has happened to a
   * consumer of this module.
   *
   * `--force` writes anyway, and prints that it did — a caller who
   * overrides the gate should have to say so out loud, in a shell
   * history somebody can read.
   */
  def main(args: Array[String]): Unit =
    val out = Paths.get("okay-intent/src/main/scala/okay/intent/MeetingModel.scala")
    val incumbent = Fit.grams(MeetingModel.json).toOption
    val verdict = Refit.propose(corpus, heldOut, incumbent)
    println(Refit.report(verdict))
    verdict match
      case Refit.Verdict.Accepted(_, _, _) =>
        Files.writeString(out, source)
        println(s"wrote $out (${Files.size(out) / 1024}KB), fitted on ${corpus.size} messages")
      case Refit.Verdict.Refused(why, _, _) if args.contains("--force") =>
        Files.writeString(out, source)
        println(s"FORCED past the gate ($why)")
        println(s"wrote $out (${Files.size(out) / 1024}KB), fitted on ${corpus.size} messages")
      case Refit.Verdict.Refused(why, _, _) =>
        println(s"NOT WRITTEN: $why")
        println("re-run with --force if you mean it, and say why in the commit")
}
