package okay.intent

import java.nio.file.{Files, Paths}

/**
 * Regenerates the shipped model (specs/intent-classify.md).
 *
 *   sbt "okayIntentJVM/Test/runMain okay.intent.MakeModel"
 *
 * The artifact in `Models` is a generated Scala source rather than a
 * resource on purpose: `okay-intent` is cross-built, and a classpath
 * resource is a JVM-only way to load a model into a module whose whole
 * point is that it needs nothing at runtime.
 *
 * It lives in the TEST scope because generating it needs the fixture,
 * and the fixture is a test. Nothing on the main path fits anything.
 */
object MakeModel {

  /** the corpus the shipped model is fitted on: the English half of
   * the labelled fixture. Not the parallel set — see the Results:
   * fifteen held-out rows per language cannot support a claim, and a
   * multilingual fit costs English three points to buy numbers I would
   * not stand behind. */
  def corpus: Seq[(String, String)] =
    IntentFixture.labelled.zipWithIndex.filter(_._2 % 2 == 1).map(_._1)

  def model: CharGrams.Trained = Fit.grams(corpus)

  /** a Scala string literal holding exactly this text */
  private def quoted(s: String): String =
    "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  def source: String =
    val lit = quoted(Fit.save(model))
    s"""package okay.intent
       |
       |/**
       | * GENERATED by `okay.intent.MakeModel` — do not edit by hand.
       | *
       | * The shipped meeting classifier, as data. See `Models` for what
       | * it is, what it scores, and what it is not.
       | */
       |private[intent] object MeetingModel:
       |  val json: String =
       |    $lit
       |""".stripMargin

  def main(args: Array[String]): Unit =
    val out = Paths.get("okay-intent/src/main/scala/okay/intent/MeetingModel.scala")
    Files.writeString(out, source)
    println(s"wrote $out (${Files.size(out) / 1024}KB), fitted on ${corpus.size} messages")
}
