package okay.cats

import _root_.cats.{Eq, Order}
import _root_.cats.effect.IO
import _root_.cats.effect.kernel.Outcome
import _root_.cats.effect.kernel.testkit.{AsyncGenerators, GenK}
import _root_.cats.effect.laws.AsyncTests
import _root_.cats.effect.testkit.TestInstances
import org.scalacheck.{Arbitrary, Cogen, Prop}
import scala.concurrent.ExecutionContext
import scala.concurrent.duration.*
import scala.language.implicitConversions
import okay.freer.!
import CatsEffect.{Program, toIO}

/**
 * cats-effect's own laws over an okay program as `F`
 * (specs/cats-effect-instances.md). The programs are generated by the
 * kernel-testkit's generic generators over OUR instance — so every
 * `uncancelable`, `onCancel`, `start`, `async`, `evalOn` in them is an
 * okay `CatsFx` — and compared by running `toIO` under one deterministic
 * `Ticker`, exactly as cats-effect checks `IO` itself. (The RuleSets
 * unfold into munit-scalacheck properties, as TestLaws does.)
 */
class TestCatsEffectLaws extends munit.ScalaCheckSuite with TestInstances { outer =>

  private def checkAll(name: String, rules: org.typelevel.discipline.Laws#RuleSet): Unit =
    for (id, prop) <- rules.all.properties do property(s"$name: $id")(prop)

  implicit val ticker: Ticker = Ticker()

  implicit def eqProgram[A: Eq]: Eq[Program[A]] = Eq.by[Program[A], IO[A]](p => toIO(p))(using eqIOA[A])
  implicit def orderProgramFD: Order[Program[FiniteDuration]] = Order.by[Program[FiniteDuration], IO[FiniteDuration]](p => toIO(p))(using orderIoFiniteDuration)
  implicit def programToProp(p: Program[Boolean]): Prop = ioBooleanToProp(toIO(p))
  implicit def cogenProgram[A: Cogen]: Cogen[Program[A]] = Cogen[Outcome[Option, Throwable, A]].contramap(p => unsafeRun(toIO(p)))

  implicit def arbitraryProgram[A: Arbitrary: Cogen]: Arbitrary[Program[A]] =
    val generators = new AsyncGenerators[Program]:
      val arbitraryE: Arbitrary[Throwable] = outer.arbitraryThrowable
      val cogenE: Cogen[Throwable] = Cogen[Throwable]
      val F: _root_.cats.effect.kernel.Async[Program] = CatsEffect.programAsync
      val arbitraryEC: Arbitrary[ExecutionContext] = outer.arbitraryExecutionContext
      val cogenFU: Cogen[Program[Unit]] = cogenProgram[Unit]
      val arbitraryFD: Arbitrary[FiniteDuration] = outer.arbitraryFiniteDuration
      // racePair reifies nondeterminism and cannot be law-tested — the
      // same exclusion cats-effect makes for IO
      override def recursiveGen[B: Arbitrary: Cogen](deeper: GenK[Program]) =
        super.recursiveGen[B](deeper).filterNot(_._1 == "racePair")
    Arbitrary(generators.generators[A])

  checkAll("Async[A ! CatsFx + Async]", AsyncTests[Program].async[Int, Int, Int](10.millis))
}

/** with the default import in scope, cats' classes over a `Program`
 * resolve to the cats-effect instance with no import of their own, and
 * over a plain program to the default monad */
class TestCatsEffectResolution extends munit.FunSuite {
  import _root_.cats.syntax.all.*

  test("cats.Monad[Program] is the cats-effect instance, unambiguously") {
    assert(summon[_root_.cats.Monad[Program]] eq CatsEffect.programAsync)
  }

  test("a plain program still gets the default monad") {
    val p: List[Int] ! okay.Pure = List(1, 2).traverse(i => okay.freer.pure[okay.Pure, Int](i * 10))
    assertEquals(!.run(p), List(10, 20))
  }
}
