;; Generated by okay.foreign.Jvm from the Scala callbacks: regenerate it, do not edit it.
(ns okay.clojure.shop)

(defn price-of
  "price_of: String -> Double"
  [a] (okay.clojure.Ops/call "price_of" a))

(defn discount
  "discount: Double -> Double"
  [a] (okay.clojure.Ops/call "discount" a))
