package okay.foreign

import okay.codec.Schema

/**
 * Haskell's side of typed effects (hs-typed-effects, specs/remote-foreign.md):
 * the effect a Haskell program may perform, written from the Scala callbacks
 * that answer it, as `Ts.ops` writes TypeScript's.
 *
 * `Hs.ops("Shop", Foreign.callbacks(priceOf, discount))` is a Haskell module
 * `Shop` holding a GADT, one constructor per operation typed by its
 * argument and answer, and its `Wire` instance for `OkayEff.send`:
 *
 * {{{
 * data Shop a where
 *   PriceOf :: String -> Shop Double
 * instance Wire Shop where
 *   request (PriceOf a0) = ("price_of", [toValue a0])
 *   reply (PriceOf _) v = fromValue v
 * }}}
 *
 * Integers, doubles, booleans, strings, lists and options map to Haskell
 * types; anything else is `Value`, open, and the comment says so. A
 * callback made without its Schemas is `Value -> op Value`.
 */
object Hs:

  /** the Haskell type of a Schema, or None where it stays `Value` */
  def haskellType(s: Schema[?]): Option[String] = s match
    case Schema.SInt | Schema.SLong | Schema.SBigInt => Some("Integer")
    case Schema.SDouble => Some("Double")
    case Schema.SBool => Some("Bool")
    case Schema.SString => Some("String")
    case l: Schema.SList[?] => haskellType(l.of()).map(t => s"[$t]")
    case v: Schema.SVector[?] => haskellType(v.of()).map(t => s"[$t]")
    case o: Schema.SOption[?] => haskellType(o.of()).map(t => s"(Maybe $t)")
    case i: Schema.SIso[?, ?] => haskellType(i.under())
    case _ => None

  /** `price_of` -> `PriceOf`: a constructor name */
  def constructor(op: String): String =
    val parts = op.split("[^A-Za-z0-9]+").filter(_.nonEmpty).map(p => p.head.toUpper.toString + p.tail)
    val name = parts.mkString
    if name.isEmpty || !name.head.isLetter then s"Op$name" else name

  /** the Haskell module declaring these callbacks as the effect `name` */
  def ops[F[+_]](name: String, cbs: Foreign.Callbacks[F]): String =
    val rows = cbs.all.map { c =>
      val (arg, res) = c.types match
        case Some((a, r)) => (haskellType(a), haskellType(r))
        case None => (None, None)
      (c.name, constructor(c.name), arg.getOrElse("Value"), res.getOrElse("Value"),
        c.types.isEmpty || arg.isEmpty || res.isEmpty)
    }
    val gadt = rows.map { (op, con, a, r, open) =>
      s"  $con :: $a -> $name $r${if open then s" -- $op: a type Haskell reads as Value" else ""}"
    }
    val requests = rows.map((op, con, _, _, _) => s"""  request ($con a0) = ("$op", [toValue a0])""")
    val replies = rows.map((_, con, _, _, _) => s"  reply ($con _) v = fromValue v")
    s"""{-# LANGUAGE GADTs #-}
       |-- Generated by okay.foreign.Hs from the Scala callbacks: regenerate it, do not edit it.
       |module $name ($name (..)) where
       |
       |import Okay (Value)
       |import OkayEff
       |
       |-- | the operations a program declaring '$name' may perform, each typed by its argument and answer
       |data $name a where
       |${gadt.mkString("\n")}
       |
       |instance Wire $name where
       |${requests.mkString("\n")}
       |${replies.mkString("\n")}
       |""".stripMargin
