package okay.foreign

import okay.{!, given}
import okay.codec.Schema

/** one parameter of a Python function, as `okay.describe` reports it */
final case class PyParam(name: String, ann: String, default: Boolean) derives Schema

/** one public function of a Python module, as `okay.describe` reports it */
final case class PySig(name: String, params: Vector[PyParam], returns: String, doc: String) derives Schema

/**
 * A Python module behind a GENERATED typed Scala object
 * (foreign-module-trait, specs/foreign-highlevel.md stage 5).
 *
 * The worker describes the module — `okay.describe`, a function of the
 * `okay` module its shim injects, reached by an ordinary call — and this
 * writes one Scala method per public function, each calling it through
 * `Py.fn`. Type hints map to types (`int` Long, `float` Double, `str`
 * String, `bool` Boolean, `bytes` Array[Byte], `list[T]` Vector[T],
 * `Optional[T]`/`T | None` Option[T]); what is not annotated, or not in
 * that list, becomes a TYPE PARAMETER (`ToPy` for an argument, `Schema`
 * for the answer), so the facade guesses nothing. A parameter with a
 * default is left out, and the method's comment says which.
 *
 * Generated rather than a trait the user writes and a macro implements:
 * the facade follows the Python code, and a change there is a diff here.
 *
 * {{{
 * sbt "okayPy/runMain okay.foreign.PyFacade statistics Stats my.pkg"
 * }}}
 */
object PyFacade:

  /** the module's public functions, described by the worker */
  def describe(module: String): Either[Condition, Vector[PySig]] ! PyEval =
    Py.fn[Vector[PySig]]("okay:describe")(module)

  private val keywords = Set("abstract", "case", "catch", "class", "def", "do", "else", "enum", "export",
    "extends", "false", "final", "finally", "for", "given", "if", "implicit", "import", "lazy", "match",
    "new", "null", "object", "override", "package", "private", "protected", "return", "sealed", "super",
    "then", "throw", "trait", "true", "try", "type", "val", "var", "while", "with", "yield")

  private def ident(n: String): String = if keywords(n) then s"`$n`" else n

  /** a type hint as a Scala type, or None when it is open */
  def scalaType(ann: String): Option[String] =
    // the wrappers peeled outside-in, applied inside-out: an annotation the
    // worker introspected nests as deep as it wrote it (stack-safety-py-r)
    val wrap = scala.collection.mutable.ArrayBuffer[String => String]()
    var a = ann.trim
    var leaf: Option[String] = None
    var open = true
    def inner(prefix: String): Option[String] =
      if a.startsWith(prefix + "[") && a.endsWith("]") then Some(a.substring(prefix.length + 1, a.length - 1))
      else None
    while open do
      a match
        case "int" => leaf = Some("Long"); open = false
        case "float" => leaf = Some("Double"); open = false
        case "str" => leaf = Some("String"); open = false
        case "bool" => leaf = Some("Boolean"); open = false
        case "bytes" => leaf = Some("Array[Byte]"); open = false
        case _ if a.endsWith(" | None") => wrap += (t => s"Option[$t]"); a = a.stripSuffix(" | None").trim
        case _ if a.startsWith("None | ") => wrap += (t => s"Option[$t]"); a = a.stripPrefix("None | ").trim
        case _ if a.startsWith("Optional[") => inner("Optional") match
          case Some(x) => wrap += (t => s"Option[$t]"); a = x.trim
          case None => open = false
        case _ if a.startsWith("list[") => inner("list") match
          case Some(x) => wrap += (t => s"Vector[$t]"); a = x.trim
          case None => open = false
        case _ if a.startsWith("List[") => inner("List") match
          case Some(x) => wrap += (t => s"Vector[$t]"); a = x.trim
          case None => open = false
        case _ if a.startsWith("Sequence[") => inner("Sequence") match
          case Some(x) => wrap += (t => s"Vector[$t]"); a = x.trim
          case None => open = false
        case _ => open = false
    leaf.map(t => wrap.reverseIterator.foldLeft(t)((acc, w) => w(acc)))

  /** the Scala source of an object calling `module`'s functions */
  def render(obj: String, pkg: String, module: String, sigs: Vector[PySig]): String =
    val b = StringBuilder()
    // what the methods below will need, so the imports carry no unused name
    // (an unused import is a warning in the user's build)
    val callable = sigs.filter(_.params.count(!_.default) <= 4)
    val needsSchema = callable.exists(s => scalaType(s.returns).isEmpty)
    val needsToPy = callable.exists(_.params.exists(p => !p.default && scalaType(p.ann).isEmpty))
    b ++= s"package $pkg\n\n"
    b ++= "import okay.!\n"
    if needsSchema then b ++= "import okay.codec.Schema\n"
    b ++= s"import okay.foreign.{${(Vector("Condition", "Py", "PyEval") ++ Option.when(needsToPy)("ToPy")).mkString(", ")}}\n\n"
    b ++= s"/** Generated by okay.foreign.PyFacade from the Python module `$module`: regenerate it, do not edit it. */\n"
    b ++= s"object $obj:\n"
    for s <- sigs do
      val required = s.params.filterNot(_.default)
      val defaulted = s.params.filter(_.default).map(_.name)
      val shown = s.params.map(p => if p.ann.isEmpty then p.name else s"${p.name}: ${p.ann}").mkString(", ")
      val ret = if s.returns.isEmpty then "" else s" -> ${s.returns}"
      b ++= "\n"
      b ++= "  /**\n"
      if s.doc.nonEmpty then b ++= s"   * ${s.doc}\n"
      b ++= s"   * Python: `${s.name}($shown)$ret`\n"
      if defaulted.nonEmpty then
        b ++= s"   * Left out, having defaults: ${defaulted.mkString(", ")}.\n"
      b ++= "   */\n"
      if required.size > 4 then
        b ++= s"  // ${s.name}: ${required.size} required parameters; call it with Py.fn(\"$module:${s.name}\") directly\n"
      else
        val out = scalaType(s.returns)
        val tparams = Vector.newBuilder[String]
        if out.isEmpty then tparams += "Out: Schema"
        val params = required.zipWithIndex.map { (p, i) =>
          scalaType(p.ann) match
            case Some(t) => s"${ident(p.name)}: $t"
            case None =>
              val t = s"A${i + 1}"
              tparams += s"$t: ToPy"
              s"${ident(p.name)}: $t"
        }
        val tps = tparams.result()
        val outT = out.getOrElse("Out")
        val tpClause = if tps.isEmpty then "" else tps.mkString("[", ", ", "]")
        val args = required.map(p => ident(p.name)).mkString(", ")
        b ++= s"  def ${ident(s.name)}$tpClause(${params.mkString(", ")}): Either[Condition, $outT] ! PyEval =\n"
        b ++= s"    Py.fn[$outT](\"$module:${s.name}\")($args)\n"
    b.result()

  /** `module Object package [python] [PYTHONPATH]`: prints the source */
  def main(args: Array[String]): Unit = args.toList match
    case module :: obj :: pkg :: rest =>
      val python = rest.headOption.getOrElse("python3")
      val env = rest.drop(1).headOption.fold(Map.empty[String, String])(p => Map("PYTHONPATH" -> p))
      val w = PySubprocess.start(python, env)
      try
        describe(module).runWith(using w.handler) match
          case Right(sigs) => print(render(obj, pkg, module, sigs))
          case Left(c) => System.err.println(s"${c.kind}: ${c.message}"); sys.exit(1)
      finally w.close()
    case _ =>
      System.err.println("usage: PyFacade <module> <Object> <package> [python] [PYTHONPATH]")
      sys.exit(2)
