package okay.codec.golden

import okay.codec.Schema

// Generated by okay.codec.TsTypes from TypeScript declarations: regenerate it, do not edit it.

final case class Line(sku: String, qty: Int, price: Double) derives Schema

final case class Order(id: Long, lines: Vector[Line], note: Option[String], total: BigInt, raw: Array[Byte]) derives Schema

enum Shape derives Schema:
  case Circle(r: Double)
  case Rect(w: Double, h: Double)

enum Tree derives Schema:
  case Leaf(v: Int)
  case Node(children: Vector[Tree])
