#!/bin/sh
# generated by okay-deploy from demo-chat's Deployment value
#
# Everything railway.json cannot say: the project, the services,
# the managed engines and the variables. Run this ONCE.
# No secret value is in this file and none ever will be.
set -e
railway init --name 'demo-chat' || echo 'project exists; `railway link` it instead'

# ---- chat
railway add --service 'chat'
railway variables --service 'chat' \
  --set 'OKAY_CHAT_PORT=8090' \
  --set 'OKAY_CHAT_DB=/app/data/okay-board.log' \
  --set 'OKAY_CHAT_APP=/app/app.js' \
  --set 'PORT=8090' \
  --skip-deploys
# railway volumes are made in the dashboard: Service -> Settings -> Volumes
#   chat: mount /app/data (1Gi)
