package okay2.codec.golden

import okay2.codec.Schema

// Generated by okay2.codec.TsTypes from TypeScript declarations: regenerate it, do not edit it.

final case class Line(sku: String, qty: Int, price: Double)
object Line {
  implicit lazy val schema: Schema[Line] = Schema.derived
}

final case class Order(id: Long, lines: Vector[Line], note: Option[String], total: BigInt, raw: Array[Byte])
object Order {
  implicit lazy val schema: Schema[Order] = Schema.derived
}

sealed trait Shape
object Shape {
  final case class Circle(r: Double) extends Shape
  final case class Rect(w: Double, h: Double) extends Shape
  implicit lazy val schema: Schema[Shape] = Schema.derived
}

sealed trait Tree
object Tree {
  final case class Leaf(v: Int) extends Tree
  final case class Node(children: Vector[Tree]) extends Tree
  implicit lazy val schema: Schema[Tree] = Schema.derived
}
