package okay.deploy

import java.nio.file.Path

/**
 * AWS, as Terraform for ECS Fargate (specs/deployment.md, stage 3).
 *
 * This is the cloud that exercises every `Need` the model has, which
 * is why it went first: a port becomes an ALB, a volume becomes EFS,
 * a database becomes RDS, a cache becomes ElastiCache, a DNS name
 * with a TLS mode becomes ACM and a Route 53 record.
 *
 * Two things are decisions rather than mapping, both in the spec. A
 * secret is NOT a Terraform resource, because `terraform apply` would
 * write its value into the state file in plaintext; it is created out
 * of band and read back by a `data` source. And the network is not
 * ours: this uses the account's default VPC through data sources and
 * builds nothing, because a real production network is a thing an
 * organisation already has.
 */
object Aws extends Target:
  val name = "aws"

  def requires(d: Deployment): Vector[String] = Vector("terraform", "aws")

  def up(dir: Path): Vector[String] =
    Vector("terraform", s"-chdir=${dir.toString}", "apply")
  def down(dir: Path): Vector[String] =
    Vector("terraform", s"-chdir=${dir.toString}", "destroy")

  def render(d: Deployment): Either[String, Vector[(String, String)]] =
    val noRegion = d.services.filter(_.region.isEmpty).map(_.name)
    if noRegion.nonEmpty then
      Left(s"aws needs a region for ${noRegion.mkString(", ")} and no target can invent one — " +
        "add Need.Region(\"eu-central-1\") (or wherever your users are)")
    else d.ordered.map { services =>
      Vector(
        "main.tf" -> align(main(d, services)),
        "setup.sh" -> setup(d, services)) ++
        services.map(s => s"${s.name}.tf" -> align(serviceTf(d, s))) ++
        d.extra.filter(_.target == name).map(e => e.path -> e.content)
    }

  // ------------------------------------------------------------------

  private def main(d: Deployment, services: Vector[Service]): String =
    val region = services.headOption.flatMap(_.region).getOrElse("")
    val zones = services.exists(_.dns.nonEmpty)
    val sb = new StringBuilder
    sb ++= s"""# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file
              |#
              |# THE NETWORK IS NOT OURS. This uses the account's DEFAULT VPC
              |# through the two data sources below and builds none of its own:
              |# private subnets, NAT, endpoints and peering are things your
              |# organisation already has opinions about. Point these two at
              |# your own module and nothing else here changes.
              |
              |terraform {
              |  required_version = ">= 1.5"
              |  required_providers {
              |    aws = {
              |      source  = "hashicorp/aws"
              |      version = "~> 5.0"
              |    }
              |  }
              |}
              |
              |provider "aws" {
              |  region = var.region
              |}
              |
              |variable "region" {
              |  description = "where this runs"
              |  type        = string
              |  default     = ${str(region)}
              |}
              |
              |""".stripMargin
    if zones then
      sb ++= """variable "zone_id" {
               |  description = "the Route 53 hosted zone for this deployment's domains — an ACM certificate validated by DNS needs one, and there is no honest way around it"
               |  type        = string
               |}
               |
               |""".stripMargin
    sb ++= s"""data "aws_vpc" "default" {
              |  default = true
              |}
              |
              |data "aws_subnets" "default" {
              |  filter {
              |    name   = "vpc-id"
              |    values = [data.aws_vpc.default.id]
              |  }
              |}
              |
              |resource "aws_ecs_cluster" "this" {
              |  name = ${str(d.name)}
              |}
              |
              |# the role ECS itself assumes to pull an image, write logs and
              |# read the secrets below — NOT the role your code runs as
              |resource "aws_iam_role" "execution" {
              |  name = "${d.name}-execution"
              |
              |  assume_role_policy = jsonencode({
              |    Version = "2012-10-17"
              |    Statement = [{
              |      Effect    = "Allow"
              |      Principal = { Service = "ecs-tasks.amazonaws.com" }
              |      Action    = "sts:AssumeRole"
              |    }]
              |  })
              |}
              |
              |resource "aws_iam_role_policy_attachment" "execution" {
              |  role       = aws_iam_role.execution.name
              |  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
              |}
              |""".stripMargin
    val secretArns = services.flatMap(secretsOf).map(n => s"data.aws_secretsmanager_secret.${ref(n)}.arn")
    if secretArns.nonEmpty then
      sb ++= s"""
                |# read-only, and only the secrets this deployment actually names
                |resource "aws_iam_role_policy" "secrets" {
                |  name = "${d.name}-secrets"
                |  role = aws_iam_role.execution.id
                |
                |  policy = jsonencode({
                |    Version = "2012-10-17"
                |    Statement = [{
                |      Effect   = "Allow"
                |      Action   = ["secretsmanager:GetSecretValue"]
                |      Resource = [${secretArns.mkString(", ")}]
                |    }]
                |  })
                |}
                |""".stripMargin
    if services.exists(s => s.databases.nonEmpty || s.caches.nonEmpty) then
      sb ++= s"""
                |resource "aws_db_subnet_group" "this" {
                |  name       = ${str(d.name)}
                |  subnet_ids = data.aws_subnets.default.ids
                |}
                |""".stripMargin
    sb.result()

  private def serviceTf(d: Deployment, s: Service): String =
    val n = s.name
    val r = ref(n)
    val full = s"${d.name}-$n"
    val sb = new StringBuilder
    sb ++= s"# generated by okay-deploy — edit the Deployment value, not this file\n\n"

    // ---- the secrets this service reads, by ARN and never by value
    for name <- secretsOf(s) do
      sb ++= s"""# created OUT OF BAND by setup.sh: `terraform apply` writes every
                |# attribute into the state file, and a secret VERSION would put
                |# the value there in plaintext
                |data "aws_secretsmanager_secret" ${str(ref(name))} {
                |  name = ${str(s"$full/$name")}
                |}
                |
                |""".stripMargin

    sb ++= s"""resource "aws_cloudwatch_log_group" ${str(r)} {
              |  name              = "/ecs/$full"
              |  retention_in_days = 30
              |}
              |
              |resource "aws_security_group" ${str(r)} {
              |  name   = "$full"
              |  vpc_id = data.aws_vpc.default.id
              |
              |""".stripMargin
    for p <- s.ports do
      sb ++= s"""  ingress {
                |    from_port       = ${p.number}
                |    to_port         = ${p.number}
                |    protocol        = "tcp"
                |${if p.public then s"""    security_groups = [aws_security_group.${r}_lb.id]"""
                  else s"""    cidr_blocks     = [data.aws_vpc.default.cidr_block]"""}
                |  }
                |
                |""".stripMargin
    sb ++= s"""  egress {
              |    from_port   = 0
              |    to_port     = 0
              |    protocol    = "-1"
              |    cidr_blocks = ["0.0.0.0/0"]
              |  }
              |}
              |
              |""".stripMargin

    // ---- EFS for every volume
    for v <- s.volumes do
      val vr = s"${r}_${ref(v.name)}"
      sb ++= s"""resource "aws_efs_file_system" ${str(vr)} {
                |  creation_token = ${str(s"$full-${v.name}")}
                |  encrypted      = true
                |
                |  tags = {
                |    Name = ${str(s"$full-${v.name}")}
                |  }
                |}
                |
                |resource "aws_efs_mount_target" ${str(vr)} {
                |  for_each = toset(data.aws_subnets.default.ids)
                |
                |  file_system_id  = aws_efs_file_system.$vr.id
                |  subnet_id       = each.value
                |  security_groups = [aws_security_group.${vr}_efs.id]
                |}
                |
                |resource "aws_security_group" ${str(s"${vr}_efs")} {
                |  name   = "$full-${v.name}-efs"
                |  vpc_id = data.aws_vpc.default.id
                |
                |  ingress {
                |    from_port       = 2049
                |    to_port         = 2049
                |    protocol        = "tcp"
                |    security_groups = [aws_security_group.$r.id]
                |  }
                |}
                |
                |""".stripMargin

    // ---- RDS, with its password read back rather than written
    for db <- s.databases do
      val dr = s"${r}_${ref(db.as)}"
      sb ++= s"""data "aws_secretsmanager_secret" ${str(s"${dr}_password")} {
                |  name = ${str(s"$full/${passwordName(db)}")}
                |}
                |
                |data "aws_secretsmanager_secret_version" ${str(s"${dr}_password")} {
                |  secret_id = data.aws_secretsmanager_secret.${dr}_password.id
                |}
                |
                |resource "aws_security_group" ${str(dr)} {
                |  name   = "$full-${db.as}"
                |  vpc_id = data.aws_vpc.default.id
                |
                |  ingress {
                |    from_port       = ${db.engine.port}
                |    to_port         = ${db.engine.port}
                |    protocol        = "tcp"
                |    security_groups = [aws_security_group.$r.id]
                |  }
                |}
                |
                |resource "aws_db_instance" ${str(dr)} {
                |  identifier             = ${str(s"$full-${db.as}")}
                |  engine                 = ${str(rdsEngine(db.engine))}
                |  engine_version         = ${str(db.version)}
                |  instance_class         = "db.t4g.micro"
                |  allocated_storage      = 20
                |  db_name                = ${str(db.database)}
                |  username               = ${str(db.as)}
                |  password               = data.aws_secretsmanager_secret_version.${dr}_password.secret_string
                |  db_subnet_group_name   = aws_db_subnet_group.this.name
                |  vpc_security_group_ids = [aws_security_group.$dr.id]
                |  skip_final_snapshot    = true
                |
                |  # a managed database is the one thing here you cannot
                |  # re-create from this file: turn these on before you rely on it
                |  backup_retention_period = 7
                |  storage_encrypted       = true
                |}
                |
                |""".stripMargin

    for c <- s.caches do
      val cr = s"${r}_${ref(c.as)}"
      sb ++= s"""resource "aws_security_group" ${str(cr)} {
                |  name   = "$full-${c.as}"
                |  vpc_id = data.aws_vpc.default.id
                |
                |  ingress {
                |    from_port       = ${c.engine.port}
                |    to_port         = ${c.engine.port}
                |    protocol        = "tcp"
                |    security_groups = [aws_security_group.$r.id]
                |  }
                |}
                |
                |resource "aws_elasticache_cluster" ${str(cr)} {
                |  cluster_id           = ${str(s"$full-${c.as}")}
                |  engine               = ${str(c.engine.toString.toLowerCase)}
                |  engine_version       = ${str(c.version)}
                |  node_type            = "cache.t4g.micro"
                |  num_cache_nodes      = 1
                |  subnet_group_name    = aws_db_subnet_group.this.name
                |  security_group_ids   = [aws_security_group.$cr.id]
                |}
                |
                |""".stripMargin

    // ---- the task definition
    sb ++= s"""resource "aws_ecs_task_definition" ${str(r)} {
              |  family                   = ${str(full)}
              |  requires_compatibilities = ["FARGATE"]
              |  network_mode             = "awsvpc"
              |  cpu                      = ${cpu(s)}
              |  memory                   = ${memory(s)}
              |  execution_role_arn       = aws_iam_role.execution.arn
              |
              |""".stripMargin
    for v <- s.volumes do
      val vr = s"${r}_${ref(v.name)}"
      sb ++= s"""  volume {
                |    name = ${str(v.name)}
                |
                |    efs_volume_configuration {
                |      file_system_id = aws_efs_file_system.$vr.id
                |      root_directory = "/"
                |    }
                |  }
                |
                |""".stripMargin
    sb ++= s"""  container_definitions = jsonencode([{
              |    name      = ${str(n)}
              |    image     = ${str(imageOf(d, s))}
              |    essential = true
              |""".stripMargin
    if s.ports.nonEmpty then
      sb ++= "    portMappings = [\n"
      for p <- s.ports do sb ++= s"      { containerPort = ${p.number}, protocol = \"tcp\" },\n"
      sb ++= "    ]\n"
    val env = s.settings.env ++ databaseEnv(s, r)
    if env.nonEmpty then
      sb ++= "    environment = [\n"
      for (k, v) <- env do sb ++= s"      { name = ${str(k)}, value = ${str(v)} },\n"
      sb ++= "    ]\n"
    val secs = secretsOf(s)
    if secs.nonEmpty then
      sb ++= "    secrets = [\n"
      for name <- secs do
        sb ++= s"      { name = ${str(name)}, valueFrom = data.aws_secretsmanager_secret.${ref(name)}.arn },\n"
      sb ++= "    ]\n"
    if s.volumes.nonEmpty then
      sb ++= "    mountPoints = [\n"
      for v <- s.volumes do
        sb ++= s"      { sourceVolume = ${str(v.name)}, containerPath = ${str(v.path)} },\n"
      sb ++= "    ]\n"
    sb ++= s"""    logConfiguration = {
              |      logDriver = "awslogs"
              |      options = {
              |        "awslogs-group"         = aws_cloudwatch_log_group.$r.name
              |        "awslogs-region"        = var.region
              |        "awslogs-stream-prefix" = "ecs"
              |      }
              |    }
              |  }])
              |}
              |
              |resource "aws_ecs_service" ${str(r)} {
              |  name            = ${str(n)}
              |  cluster         = aws_ecs_cluster.this.id
              |  task_definition = aws_ecs_task_definition.$r.arn
              |  desired_count   = ${s.scale.replicas}
              |  launch_type     = "FARGATE"
              |
              |  network_configuration {
              |    subnets          = data.aws_subnets.default.ids
              |    security_groups  = [aws_security_group.$r.id]
              |    assign_public_ip = true
              |  }
              |""".stripMargin
    val public = s.ports.find(_.public)
    public.foreach { p =>
      sb ++= s"""
                |  load_balancer {
                |    target_group_arn = aws_lb_target_group.$r.arn
                |    container_name   = ${str(n)}
                |    container_port   = ${p.number}
                |  }
                |
                |  depends_on = [aws_lb_listener.${r}_http]
                |""".stripMargin
    }
    sb ++= "}\n"

    // ---- the load balancer, when anything is public
    public.foreach { p =>
      sb ++= s"""
                |resource "aws_security_group" ${str(s"${r}_lb")} {
                |  name   = "$full-lb"
                |  vpc_id = data.aws_vpc.default.id
                |
                |  ingress {
                |    from_port   = 80
                |    to_port     = 80
                |    protocol    = "tcp"
                |    cidr_blocks = ["0.0.0.0/0"]
                |  }
                |
                |""".stripMargin
      if s.dns.nonEmpty then
        sb ++= """  ingress {
                 |    from_port   = 443
                 |    to_port     = 443
                 |    protocol    = "tcp"
                 |    cidr_blocks = ["0.0.0.0/0"]
                 |  }
                 |
                 |""".stripMargin
      sb ++= s"""  egress {
                |    from_port   = 0
                |    to_port     = 0
                |    protocol    = "-1"
                |    cidr_blocks = ["0.0.0.0/0"]
                |  }
                |}
                |
                |resource "aws_lb" ${str(r)} {
                |  name               = ${str(full.take(32))}
                |  load_balancer_type = "application"
                |  subnets            = data.aws_subnets.default.ids
                |  security_groups    = [aws_security_group.${r}_lb.id]
                |}
                |
                |resource "aws_lb_target_group" ${str(r)} {
                |  name        = ${str(full.take(32))}
                |  port        = ${p.number}
                |  protocol    = "HTTP"
                |  target_type = "ip"
                |  vpc_id      = data.aws_vpc.default.id
                |
                |  health_check {
                |    path                = ${str(s.health.readinessPath)}
                |    healthy_threshold   = 2
                |    unhealthy_threshold = 3
                |    interval            = 10
                |  }
                |}
                |
                |""".stripMargin
      if s.dns.isEmpty then
        sb ++= s"""resource "aws_lb_listener" ${str(s"${r}_http")} {
                  |  load_balancer_arn = aws_lb.$r.arn
                  |  port              = 80
                  |  protocol          = "HTTP"
                  |
                  |  default_action {
                  |    type             = "forward"
                  |    target_group_arn = aws_lb_target_group.$r.arn
                  |  }
                  |}
                  |
                  |output "${r}_url" {
                  |  description = "no Need.Dns, so this is the address: point your own DNS at it"
                  |  value       = "http://$${aws_lb.$r.dns_name}"
                  |}
                  |""".stripMargin
      else
        sb ++= s"""resource "aws_acm_certificate" ${str(r)} {
                  |  domain_name               = ${str(s.dns.head)}
                  |  subject_alternative_names = [${s.dns.drop(1).map(str).mkString(", ")}]
                  |  validation_method         = "DNS"
                  |
                  |  lifecycle {
                  |    create_before_destroy = true
                  |  }
                  |}
                  |
                  |resource "aws_route53_record" ${str(s"${r}_validation")} {
                  |  for_each = {
                  |    for o in aws_acm_certificate.$r.domain_validation_options : o.domain_name => {
                  |      name   = o.resource_record_name
                  |      record = o.resource_record_value
                  |      type   = o.resource_record_type
                  |    }
                  |  }
                  |
                  |  zone_id = var.zone_id
                  |  name    = each.value.name
                  |  type    = each.value.type
                  |  records = [each.value.record]
                  |  ttl     = 60
                  |}
                  |
                  |resource "aws_acm_certificate_validation" ${str(r)} {
                  |  certificate_arn         = aws_acm_certificate.$r.arn
                  |  validation_record_fqdns = [for r in aws_route53_record.${r}_validation : r.fqdn]
                  |}
                  |
                  |# port 80 only redirects: a service with a certificate should
                  |# not also answer without one
                  |resource "aws_lb_listener" ${str(s"${r}_http")} {
                  |  load_balancer_arn = aws_lb.$r.arn
                  |  port              = 80
                  |  protocol          = "HTTP"
                  |
                  |  default_action {
                  |    type = "redirect"
                  |
                  |    redirect {
                  |      port        = "443"
                  |      protocol    = "HTTPS"
                  |      status_code = "HTTP_301"
                  |    }
                  |  }
                  |}
                  |
                  |resource "aws_lb_listener" ${str(s"${r}_https")} {
                  |  load_balancer_arn = aws_lb.$r.arn
                  |  port              = 443
                  |  protocol          = "HTTPS"
                  |  certificate_arn   = aws_acm_certificate_validation.$r.certificate_arn
                  |
                  |  default_action {
                  |    type             = "forward"
                  |    target_group_arn = aws_lb_target_group.$r.arn
                  |  }
                  |}
                  |
                  |""".stripMargin
        for (host, i) <- s.dns.zipWithIndex do
          sb ++= s"""resource "aws_route53_record" ${str(s"${r}_alias_$i")} {
                    |  zone_id = var.zone_id
                    |  name    = ${str(host)}
                    |  type    = "A"
                    |
                    |  alias {
                    |    name                   = aws_lb.$r.dns_name
                    |    zone_id                = aws_lb.$r.zone_id
                    |    evaluate_target_health = true
                    |  }
                    |}
                    |
                    |""".stripMargin
    }
    sb.result()

  // ---- the secrets Terraform must never hold -------------------------

  private[deploy] def secretsOf(s: Service): Vector[String] =
    s.secrets.flatMap(Targets.envVarOf).distinct

  private[deploy] def passwordName(db: Need.Database): String =
    Settings.envName("", s"${db.as}_password")

  private def setup(d: Deployment, services: Vector[Service]): String =
    val sb = new StringBuilder
    sb ++= s"""#!/bin/sh
              |# generated by okay-deploy from ${d.name}'s Deployment value
              |#
              |# Every secret this deployment reads, created BEFORE terraform runs.
              |#
              |# Why here and not in a .tf file: `terraform apply` writes every
              |# resource attribute into the state file, and a secret version
              |# would put the VALUE there in plaintext — in S3, on a laptop, in
              |# a CI artifact. Terraform reads these back through a data source
              |# and never holds one.
              |#
              |# No value is in this file and none ever will be.
              |set -e
              |REGION=$${AWS_REGION:-${services.headOption.flatMap(_.region).getOrElse("")}}
              |
              |create() { # name, value, description
              |  aws secretsmanager create-secret --region "$$REGION" \\
              |    --name "$$1" --secret-string "$$2" --description "$$3" >/dev/null 2>&1 \\
              |  || aws secretsmanager put-secret-value --region "$$REGION" \\
              |    --secret-id "$$1" --secret-string "$$2" >/dev/null
              |  echo "  $$1"
              |}
              |
              |""".stripMargin
    var any = false
    for s <- services do
      val full = s"${d.name}-${s.name}"
      val names = secretsOf(s).map(n => n -> s"read by ${s.name} as $n") ++
        s.databases.map(db => passwordName(db) -> s"the master password for the ${db.engine} beside ${s.name}")
      if names.nonEmpty then
        any = true
        sb ++= s"echo ${q(s"${s.name}:")}\n"
        for (n, why) <- names do
          sb ++= s"""create ${q(s"$full/$n")} "$${$n:?set $n in your own environment — ${Shell.prompt(why)}}" ${q(why)}\n"""
        sb ++= "\n"
    if !any then sb ++= "echo 'this deployment reads no secrets; nothing to create.'\n"
    sb.result()

  // ---- shared -------------------------------------------------------

  private def imageOf(d: Deployment, s: Service): String = s.run match
    case Run.Image(repo, tag) => s"$repo:$tag"
    case Run.Module(_, _, _, _) => s"${d.name}/${s.name}:latest"

  /** what a service is told about the database beside it — one URL,
   * built where the engine is known. An interpolation rather than a
   * literal, because the endpoint is not known until apply. */
  private def databaseEnv(s: Service, r: String): Vector[(String, String)] =
    s.databases.map { db =>
      val dr = s"${r}_${ref(db.as)}"
      val url = db.engine match
        case Engine.Postgres => s"jdbc:postgresql://$${aws_db_instance.$dr.endpoint}/${db.database}"
        case Engine.Mongo => s"mongodb://$${aws_db_instance.$dr.endpoint}/${db.database}"
        case _ => s"$${aws_db_instance.$dr.endpoint}"
      Settings.envName("", s"${db.as}_url") -> url
    } ++ s.caches.map { c =>
      val cr = s"${r}_${ref(c.as)}"
      Settings.envName("", s"${c.as}_url") ->
        s"$${aws_elasticache_cluster.$cr.cache_nodes[0].address}:${c.engine.port}"
    }

  private def rdsEngine(e: Engine): String = e match
    case Engine.Postgres => "postgres"
    case Engine.Mongo => "docdb"
    case other => other.toString.toLowerCase

  private def cpu(s: Service): String =
    s.resources.map(_.cpuLimit).map(c => if c.endsWith("m") then c.dropRight(1) else (c.toDouble * 1024).toInt.toString)
      .getOrElse("256")

  private def memory(s: Service): String =
    s.resources.map(_.memoryLimit).map(m =>
      if m.toLowerCase.endsWith("gi") then (m.dropRight(2).toInt * 1024).toString
      else m.toLowerCase.stripSuffix("mi")).getOrElse("512")

  /**
   * What `terraform fmt` does to consecutive attributes: line the `=`
   * up within each run.
   *
   * Written because `terraform fmt -check` caught two blocks where the
   * padding was typed by hand and wrong — and hand-typed padding is
   * wrong again the moment a name changes. Doing it here means the
   * renderer cannot produce a file fmt would rewrite, which matters
   * for a file people read and diff.
   */
  private[deploy] def align(text: String): String =
    val attr = """^(\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*)=(\s.*)$""".r
    val lines = text.linesIterator.toVector
    val out = Array.fill(lines.length)("")
    var i = 0
    while i < lines.length do
      lines(i) match
        // an attribute whose value OPENS a bracket it does not close
        // spans lines, and fmt does not align it with its neighbours
        case attr(_, _, _, rest) if !balanced(rest) =>
          out(i) = lines(i).replaceFirst("""\s*=""", " =")
          i += 1
        case attr(indent, _, _, _) =>
          var j = i
          val run = scala.collection.mutable.ArrayBuffer.empty[(String, String, String)]
          while j < lines.length && (lines(j) match
            case attr(ind2, k2, _, r2) if ind2 == indent && balanced(r2) => run += ((ind2, k2, r2)); true
            case _ => false) do j += 1
          val width = run.map(_._2.length).max
          for ((ind, k, r), off) <- run.zipWithIndex do
            out(i + off) = ind + k + " " * (width - k.length) + " =" + r
          i = j
        case other =>
          out(i) = other
          i += 1
    out.mkString("\n") + (if text.endsWith("\n") then "\n" else "")

  /** does this fragment close every bracket it opens? Brackets inside
   * a string literal are text, not structure. */
  private def balanced(s: String): Boolean =
    var depth = 0
    var inStr = false
    var esc = false
    for c <- s do
      if esc then esc = false
      else if inStr then
        if c == '\\' then esc = true else if c == '"' then inStr = false
      else c match
        case '"' => inStr = true
        case '{' | '[' | '(' => depth += 1
        case '}' | ']' | ')' => depth -= 1
        case _ => ()
    depth <= 0

  /** a Terraform identifier: letters, digits and underscores */
  private def ref(s: String): String =
    val cleaned = s.map(c => if c.isLetterOrDigit then c else '_')
    if cleaned.headOption.exists(_.isDigit) then s"_$cleaned" else cleaned

  private def str(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  private def q(s: String): String = "'" + s.replace("'", "'\\''") + "'"
