package okay.deploy

import java.nio.file.Path

/**
 * Azure, as Terraform for Container Apps (specs/deployment.md, stage
 * 3).
 *
 * The counter-example that keeps `gcp`'s volume refusal honest: a
 * `Need.Volume` works here, because Container Apps mounts an Azure
 * Files share and that share IS a real filesystem — atomic rename,
 * locking, the two things okay-persist's log needs and gcsfuse does
 * not have.
 */
object Azure extends Target:
  val name = "azure"

  def requires(d: Deployment): Vector[String] = Vector("terraform", "az")

  def up(dir: Path): Vector[String] = Vector("terraform", s"-chdir=${dir.toString}", "apply")
  def down(dir: Path): Vector[String] = Vector("terraform", s"-chdir=${dir.toString}", "destroy")

  def render(d: Deployment): Either[String, Vector[(String, String)]] =
    val noRegion = d.services.filter(_.region.isEmpty).map(_.name)
    if noRegion.nonEmpty then
      Left(s"azure needs a location for ${noRegion.mkString(", ")} and no target can invent one — " +
        "add Need.Region(\"westeurope\") (or wherever your users are)")
    else d.ordered.map { services =>
      Vector(
        "main.tf" -> Aws.align(main(d, services)),
        "setup.sh" -> setup(d, services)) ++
        services.map(s => s"${s.name}.tf" -> Aws.align(serviceTf(d, s))) ++
        d.extra.filter(_.target == name).map(e => e.path -> e.content)
    }

  // ------------------------------------------------------------------

  private def main(d: Deployment, services: Vector[Service]): String =
    val region = services.headOption.flatMap(_.region).getOrElse("")
    val sb = new StringBuilder
    sb ++= s"""# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file
              |#
              |# THE RESOURCE GROUP IS OURS AND NOTHING ELSE IS: a group is
              |# the unit Azure deletes as one, so a deployment owning its own
              |# is the honest boundary. The subscription, the network and the
              |# DNS zone are yours.
              |
              |terraform {
              |  required_version = ">= 1.5"
              |  required_providers {
              |    azurerm = {
              |      source  = "hashicorp/azurerm"
              |      version = "~> 4.0"
              |    }
              |  }
              |}
              |
              |provider "azurerm" {
              |  features {}
              |}
              |
              |variable "location" {
              |  description = "where this runs"
              |  type        = string
              |  default     = ${str(region)}
              |}
              |
              |variable "vault_name" {
              |  description = "the Key Vault holding this deployment's secrets — created by setup.sh, not by Terraform"
              |  type        = string
              |}
              |
              |resource "azurerm_resource_group" "this" {
              |  name     = ${str(d.name)}
              |  location = var.location
              |}
              |
              |resource "azurerm_log_analytics_workspace" "this" {
              |  name                = ${str(s"${d.name}-logs")}
              |  location            = azurerm_resource_group.this.location
              |  resource_group_name = azurerm_resource_group.this.name
              |  sku                 = "PerGB2018"
              |  retention_in_days   = 30
              |}
              |
              |resource "azurerm_container_app_environment" "this" {
              |  name                       = ${str(d.name)}
              |  location                   = azurerm_resource_group.this.location
              |  resource_group_name        = azurerm_resource_group.this.name
              |  log_analytics_workspace_id = azurerm_log_analytics_workspace.this.id
              |}
              |
              |data "azurerm_key_vault" "this" {
              |  name                = var.vault_name
              |  resource_group_name = azurerm_resource_group.this.name
              |}
              |""".stripMargin
    if services.exists(_.volumes.nonEmpty) then
      sb ++= s"""
                |# a Need.Volume is an Azure Files share, which is a REAL
                |# filesystem — atomic rename and locking, the two things
                |# okay-persist's log needs and object storage does not have
                |resource "azurerm_storage_account" "this" {
                |  name                     = ${str(sanitize(d.name) + "store")}
                |  resource_group_name      = azurerm_resource_group.this.name
                |  location                 = azurerm_resource_group.this.location
                |  account_tier             = "Standard"
                |  account_replication_type = "LRS"
                |}
                |""".stripMargin
    sb.result()

  private def serviceTf(d: Deployment, s: Service): String =
    val r = ref(s.name)
    val full = s"${d.name}-${s.name}"
    val sb = new StringBuilder
    sb ++= "# generated by okay-deploy — edit the Deployment value, not this file\n\n"

    for name <- Aws.secretsOf(s) do
      sb ++= s"""# created OUT OF BAND by setup.sh: `terraform apply` writes every
                |# attribute into the state file, and a secret's VALUE would be
                |# in it in plaintext
                |data "azurerm_key_vault_secret" ${str(ref(name))} {
                |  name         = ${str(kvName(s"$full-$name"))}
                |  key_vault_id = data.azurerm_key_vault.this.id
                |}
                |
                |""".stripMargin

    for db <- s.databases do
      val dr = s"${r}_${ref(db.as)}"
      sb ++= s"""data "azurerm_key_vault_secret" ${str(s"${dr}_password")} {
                |  name         = ${str(kvName(s"$full-${Aws.passwordName(db)}"))}
                |  key_vault_id = data.azurerm_key_vault.this.id
                |}
                |
                |resource "azurerm_postgresql_flexible_server" ${str(dr)} {
                |  name                          = ${str(s"$full-${db.as}")}
                |  resource_group_name           = azurerm_resource_group.this.name
                |  location                      = azurerm_resource_group.this.location
                |  version                       = ${str(db.version.takeWhile(_ != '.'))}
                |  administrator_login           = ${str(db.as)}
                |  administrator_password        = data.azurerm_key_vault_secret.${dr}_password.value
                |  storage_mb                    = 32768
                |  sku_name                      = "B_Standard_B1ms"
                |  public_network_access_enabled = false
                |
                |  # a managed database is the one thing here you cannot
                |  # re-create from this file
                |  backup_retention_days = 7
                |}
                |
                |resource "azurerm_postgresql_flexible_server_database" ${str(dr)} {
                |  name      = ${str(db.database)}
                |  server_id = azurerm_postgresql_flexible_server.$dr.id
                |}
                |
                |""".stripMargin

    for c <- s.caches do
      val cr = s"${r}_${ref(c.as)}"
      sb ++= s"""resource "azurerm_redis_cache" ${str(cr)} {
                |  name                = ${str(s"$full-${c.as}")}
                |  resource_group_name = azurerm_resource_group.this.name
                |  location            = azurerm_resource_group.this.location
                |  capacity            = 0
                |  family              = "C"
                |  sku_name            = "Basic"
                |}
                |
                |""".stripMargin

    for v <- s.volumes do
      val vr = s"${r}_${ref(v.name)}"
      sb ++= s"""resource "azurerm_storage_share" ${str(vr)} {
                |  name               = ${str(s"$full-${v.name}")}
                |  storage_account_id = azurerm_storage_account.this.id
                |  quota              = ${v.size.toLowerCase.filter(_.isDigit)}
                |}
                |
                |resource "azurerm_container_app_environment_storage" ${str(vr)} {
                |  name                         = ${str(s"$full-${v.name}")}
                |  container_app_environment_id = azurerm_container_app_environment.this.id
                |  account_name                 = azurerm_storage_account.this.name
                |  share_name                   = azurerm_storage_share.$vr.name
                |  access_key                   = azurerm_storage_account.this.primary_access_key
                |  access_mode                  = "ReadWrite"
                |}
                |
                |""".stripMargin

    sb ++= s"""resource "azurerm_container_app" ${str(r)} {
              |  name                         = ${str(full)}
              |  container_app_environment_id = azurerm_container_app_environment.this.id
              |  resource_group_name          = azurerm_resource_group.this.name
              |  revision_mode                = "Single"
              |
              |""".stripMargin
    for n <- Aws.secretsOf(s) do
      sb ++= s"""  secret {
                |    name  = ${str(n.toLowerCase.replace('_', '-'))}
                |    value = data.azurerm_key_vault_secret.${ref(n)}.value
                |  }
                |
                |""".stripMargin
    sb ++= s"""  template {
              |    min_replicas = ${s.scale.replicas}
              |
              |    container {
              |      name   = ${str(s.name)}
              |      image  = ${str(imageOf(d, s))}
              |      cpu    = ${cpu(s)}
              |      memory = ${str(memory(s))}
              |""".stripMargin
    for (k, v) <- s.settings.env ++ databaseEnv(s, r) do
      sb ++= s"""
                |      env {
                |        name  = ${str(k)}
                |        value = ${str(v)}
                |      }
                |""".stripMargin
    for n <- Aws.secretsOf(s) do
      sb ++= s"""
                |      env {
                |        name        = ${str(n)}
                |        secret_name = ${str(n.toLowerCase.replace('_', '-'))}
                |      }
                |""".stripMargin
    for v <- s.volumes do
      sb ++= s"""
                |      volume_mounts {
                |        name = ${str(v.name)}
                |        path = ${str(v.path)}
                |      }
                |""".stripMargin
    s.mainPort.foreach { port =>
      sb ++= s"""
                |      liveness_probe {
                |        transport = "HTTP"
                |        port      = $port
                |        path      = ${str(s.health.livenessPath)}
                |      }
                |
                |      readiness_probe {
                |        transport = "HTTP"
                |        port      = $port
                |        path      = ${str(s.health.readinessPath)}
                |      }
                |""".stripMargin
    }
    sb ++= "    }\n"
    for v <- s.volumes do
      val vr = s"${r}_${ref(v.name)}"
      sb ++= s"""
                |    volume {
                |      name         = ${str(v.name)}
                |      storage_type = "AzureFile"
                |      storage_name = azurerm_container_app_environment_storage.$vr.name
                |    }
                |""".stripMargin
    sb ++= "  }\n"
    s.ports.find(_.public).foreach { p =>
      sb ++= s"""
                |  # its own name carries a managed certificate from the moment
                |  # it exists, which is the difference from an ALB
                |  ingress {
                |    external_enabled = true
                |    target_port      = ${p.number}
                |
                |    traffic_weight {
                |      latest_revision = true
                |      percentage      = 100
                |    }
                |  }
                |""".stripMargin
    }
    sb ++= "}\n"

    if s.ports.exists(_.public) then
      sb ++= s"""
                |output "${r}_url" {
                |  description = "the platform's own name, with a managed certificate from the moment it exists"
                |  value       = "https://$${azurerm_container_app.$r.ingress[0].fqdn}"
                |}
                |""".stripMargin
    if s.dns.nonEmpty then
      sb ++= s"""
                |# A CUSTOM DOMAIN NEEDS VERIFICATION FIRST: a TXT record
                |# proving you own ${s.dns.mkString(", ")}, checked by Azure,
                |# before a managed certificate is issued. No Terraform
                |# resource verifies a domain for you — add the records the
                |# portal names, then declare
                |# azurerm_container_app_custom_domain here.
                |""".stripMargin
    sb.result()

  // ------------------------------------------------------------------

  private def setup(d: Deployment, services: Vector[Service]): String =
    val sb = new StringBuilder
    sb ++= s"""#!/bin/sh
              |# generated by okay-deploy from ${d.name}'s Deployment value
              |#
              |# The Key Vault and every secret in it, created BEFORE terraform
              |# runs. Terraform READS these; it never holds one, because
              |# `apply` writes every attribute into the state file.
              |#
              |# No value is in this file and none ever will be.
              |set -e
              |GROUP=$${AZURE_RESOURCE_GROUP:-${d.name}}
              |VAULT=$${AZURE_VAULT:?set AZURE_VAULT to the Key Vault name — it is globally unique}
              |LOCATION=$${AZURE_LOCATION:-${services.headOption.flatMap(_.region).getOrElse("")}}
              |
              |az group create --name "$$GROUP" --location "$$LOCATION" >/dev/null
              |az keyvault create --name "$$VAULT" --resource-group "$$GROUP" --location "$$LOCATION" >/dev/null 2>&1 || true
              |
              |create() { # name, value
              |  az keyvault secret set --vault-name "$$VAULT" --name "$$1" --value "$$2" >/dev/null
              |  echo "  $$1"
              |}
              |
              |""".stripMargin
    var any = false
    for s <- services do
      val full = s"${d.name}-${s.name}"
      val names = Aws.secretsOf(s).map(n => n -> s"read by ${s.name} as $n") ++
        s.databases.map(db => Aws.passwordName(db) -> s"the password for the ${db.engine} beside ${s.name}")
      if names.nonEmpty then
        any = true
        sb ++= s"echo ${q(s"${s.name}:")}\n"
        for (n, why) <- names do
          sb ++= s"""create ${q(kvName(s"$full-$n"))} "$${$n:?set $n in your own environment — ${Shell.prompt(why)}}"\n"""
        sb ++= "\n"
    if !any then sb ++= "echo 'this deployment reads no secrets; the vault above is still where they would go.'\n"
    sb.result()

  private def imageOf(d: Deployment, s: Service): String = s.run match
    case Run.Image(repo, tag) => s"$repo:$tag"
    case _: Run.Module => s"${d.name}.azurecr.io/${s.name}:latest"

  private def databaseEnv(s: Service, r: String): Vector[(String, String)] =
    s.databases.map { db =>
      val dr = s"${r}_${ref(db.as)}"
      val host = s"$${azurerm_postgresql_flexible_server.$dr.fqdn}"
      val url = db.engine match
        case Engine.Postgres => s"jdbc:postgresql://$host:${db.engine.port}/${db.database}"
        case Engine.Mongo => s"mongodb://$host:${db.engine.port}/${db.database}"
        case _ => host
      Settings.envName("", s"${db.as}_url") -> url
    } ++ s.caches.map { c =>
      val cr = s"${r}_${ref(c.as)}"
      Settings.envName("", s"${c.as}_url") ->
        s"$${azurerm_redis_cache.$cr.hostname}:$${azurerm_redis_cache.$cr.ssl_port}"
    }

  /** a Key Vault secret name: letters, digits and dashes only */
  private[deploy] def kvName(s: String): String =
    s.map(c => if c.isLetterOrDigit then c else '-').replaceAll("-+", "-").stripPrefix("-").stripSuffix("-")

  /** a storage account name: lower-case letters and digits, no more */
  private def sanitize(s: String): String = s.filter(_.isLetterOrDigit).toLowerCase.take(16)

  private def cpu(s: Service): String =
    s.resources.map(_.cpuLimit).map { c =>
      if c.endsWith("m") then (c.dropRight(1).toDouble / 1000.0).toString else c.toDouble.toString
    }.getOrElse("0.25")

  private def memory(s: Service): String =
    s.resources.map(_.memoryLimit).map { m =>
      if m.toLowerCase.endsWith("gi") then s"${m.dropRight(2)}Gi"
      else s"${math.max(1, m.toLowerCase.stripSuffix("mi").toInt / 1024)}Gi"
    }.getOrElse("0.5Gi")

  private def ref(s: String): String =
    val cleaned = s.map(c => if c.isLetterOrDigit then c else '_')
    if cleaned.headOption.exists(_.isDigit) then s"_$cleaned" else cleaned

  private def str(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
  private def q(s: String): String = "'" + s.replace("'", "'\\''") + "'"
