package okay.deploy

import java.nio.file.Path

/**
 * A Kubernetes cluster, through a Helm chart (specs/deployment.md,
 * stage 1).
 *
 * This is the one target whose own model has the same shape as the
 * `Deployment` value, so the mapping is mostly naming: a service is a
 * Deployment and a Service, settings are a ConfigMap taken whole, a
 * volume is a PVC, a DNS name with a TLS mode is an Ingress, a
 * neighbour is nothing at all because the service name IS the DNS
 * name inside a cluster.
 *
 * Four things are decisions rather than naming, and each is in the
 * spec with its reason: the Secret is NOT templated (an upgrade would
 * overwrite the real one with blanks), a self-signed certificate is
 * refused here, a database is rendered but says in the file what it
 * is, and the templates are per service rather than one `range` over
 * a map nobody can debug.
 */
object Cluster extends Target:
  val name = "cluster"

  def requires(d: Deployment): Vector[String] = Vector("kubectl", "helm")

  def up(dir: Path): Vector[String] =
    Vector("helm", "upgrade", "--install", releaseOf(dir), dir.toString)

  def down(dir: Path): Vector[String] = Vector("helm", "uninstall", releaseOf(dir))

  /** the release is the chart's directory's grandparent — `<app>/
   * deploy/cluster` — which is the deployment's own name; a caller
   * with a different opinion runs helm themselves */
  private def releaseOf(dir: Path): String =
    Option(dir.getParent).flatMap(p => Option(p.getParent)).map(_.getFileName.toString).getOrElse("okay")

  // ------------------------------------------------------------------

  def render(d: Deployment): Either[String, Vector[(String, String)]] =
    val refused = d.services.flatMap { s =>
      s.tls match
        case Some(TlsMode.SelfSigned) => Vector(
          s"${s.name} asks for a self-signed certificate and the cluster target will not render one — " +
            "behind an ingress that is a browser warning for every visitor; " +
            "use Tls(Acme) for cert-manager, or Tls(Files) with a Secret you already hold")
        case _ => Vector.empty
    }
    if refused.nonEmpty then Left(refused.mkString("; "))
    else d.ordered.map { services =>
      Vector(
        "Chart.yaml" -> chart(d),
        "values.yaml" -> values(d, services),
        "secrets.sh" -> secretsScript(d)) ++
        services.flatMap(templates) ++
        d.extra.filter(_.target == name).map(e => e.path -> e.content)
    }

  // ---- the chart ----------------------------------------------------

  private def chart(d: Deployment): String =
    s"""# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file
       |apiVersion: v2
       |name: ${d.name}
       |description: ${d.name} — ${d.services.length} service${if d.services.length == 1 then "" else "s"}, rendered from one value
       |type: application
       |version: 0.1.0
       |appVersion: "0.1.0"
       |""".stripMargin

  private def values(d: Deployment, services: Vector[Service]): String =
    val sb = new StringBuilder
    sb ++= s"# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file\n"
    sb ++= "# what an operator overrides per install lives HERE; everything\n"
    sb ++= "# else is in the templates, concrete, where it can be read.\n"
    for s <- services do
      sb ++= s"${s.name}:\n"
      sb ++= "  image:\n"
      val (repo, tag) = s.run match
        case Run.Image(r, t) => (r, t)
        case _: Run.Module => (s"${d.name}/${s.name}", "local")
      sb ++= s"    repository: ${quote(repo)}\n    tag: ${quote(tag)}\n    pullPolicy: IfNotPresent\n"
      sb ++= s"  replicaCount: ${s.scale.replicas}\n"
      s.resources match
        case None => sb ++= "  resources: {}\n"
        case Some(r) =>
          sb ++= "  resources:\n    requests:\n"
          sb ++= s"      cpu: ${quote(r.cpuRequest)}\n      memory: ${quote(r.memoryRequest)}\n"
          sb ++= "    limits:\n"
          sb ++= s"      cpu: ${quote(r.cpuLimit)}\n      memory: ${quote(r.memoryLimit)}\n"
      for v <- s.volumes do
        sb ++= s"  ${v.name}Size: ${quote(v.size)}\n"
      for db <- s.databases do
        sb ++= s"  ${db.as}Size: ${quote("8Gi")}\n"
    // the ClusterIssuer belongs to the CLUSTER, not to this chart, so
    // it is a value with the conventional default rather than a
    // constant in a template
    if services.exists(_.tls.contains(TlsMode.Acme)) then
      sb ++= "\n# cert-manager's ClusterIssuer — the cluster's, not ours\ningress:\n  issuer: \"letsencrypt-prod\"\n"
    sb.result()

  // ---- the templates, one file per thing ----------------------------

  private def templates(s: Service): Vector[(String, String)] =
    Vector(s"templates/${s.name}-deployment.yaml" -> deployment(s)) ++
      (if s.settings.all.nonEmpty || s.databases.nonEmpty || s.caches.nonEmpty
       then Vector(s"templates/${s.name}-config.yaml" -> configMap(s)) else Vector.empty) ++
      (if s.ports.nonEmpty then Vector(s"templates/${s.name}-service.yaml" -> service(s)) else Vector.empty) ++
      s.volumes.map(v => s"templates/${s.name}-${v.name}-pvc.yaml" -> pvc(s, v)) ++
      (if s.dns.nonEmpty then Vector(s"templates/${s.name}-ingress.yaml" -> ingress(s)) else Vector.empty) ++
      s.databases.map(db => s"templates/${s.name}-${db.as}.yaml" -> database(s, db)) ++
      s.caches.map(c => s"templates/${s.name}-${c.as}.yaml" -> cache(s, c))

  private def head(s: Service): String =
    s"""{{- $$v := index .Values ${quote(s.name)} -}}
       |# generated by okay-deploy — edit the Deployment value, not this file
       |""".stripMargin

  private def deployment(s: Service): String =
    val sb = new StringBuilder
    sb ++= head(s)
    sb ++= s"""apiVersion: apps/v1
              |kind: Deployment
              |metadata:
              |  name: {{ .Release.Name }}-${s.name}
              |  labels:
              |    app.kubernetes.io/name: ${s.name}
              |    app.kubernetes.io/instance: {{ .Release.Name }}
              |    app.kubernetes.io/managed-by: {{ .Release.Service }}
              |spec:
              |  replicas: {{ $$v.replicaCount }}
              |  selector:
              |    matchLabels:
              |      app.kubernetes.io/name: ${s.name}
              |      app.kubernetes.io/instance: {{ .Release.Name }}
              |  template:
              |    metadata:
              |      labels:
              |        app.kubernetes.io/name: ${s.name}
              |        app.kubernetes.io/instance: {{ .Release.Name }}
              |${metrics(s)}    spec:
              |      containers:
              |        - name: ${s.name}
              |          image: "{{ $$v.image.repository }}:{{ $$v.image.tag }}"
              |          imagePullPolicy: {{ $$v.image.pullPolicy }}
              |""".stripMargin
    if s.ports.nonEmpty then
      sb ++= "          ports:\n"
      for p <- s.ports do sb ++= s"            - containerPort: ${p.number}\n"
    if s.settings.all.nonEmpty || s.databases.nonEmpty || s.caches.nonEmpty then
      sb ++= "          envFrom:\n"
      sb ++= s"            - configMapRef:\n                name: {{ .Release.Name }}-${s.name}\n"
    if s.secrets.nonEmpty then
      // a secret is a REFERENCE: the chart names a Secret it does NOT
      // own, so `helm upgrade` cannot overwrite it with blanks
      sb ++= "          env:\n"
      for sec <- s.secrets; v <- Targets.envVarOf(sec) do
        sb ++= s"            - name: $v\n"
        sb ++= s"              valueFrom:\n                secretKeyRef:\n"
        sb ++= s"                  name: {{ .Release.Name }}-secrets\n                  key: $v\n"
    if s.volumes.nonEmpty then
      sb ++= "          volumeMounts:\n"
      for v <- s.volumes do
        sb ++= s"            - name: ${v.name}\n              mountPath: ${quote(v.path)}\n"
    s.mainPort.foreach { port =>
      sb ++= s"""          livenessProbe:
                |            httpGet:
                |              path: ${s.health.livenessPath}
                |              port: $port
                |            periodSeconds: 10
                |          readinessProbe:
                |            httpGet:
                |              path: ${s.health.readinessPath}
                |              port: $port
                |            periodSeconds: 10
                |          startupProbe:
                |            httpGet:
                |              path: ${s.health.livenessPath}
                |              port: $port
                |            periodSeconds: 5
                |            failureThreshold: ${math.max(1, s.health.startupSeconds / 5)}
                |""".stripMargin
    }
    sb ++= "          resources:\n            {{- toYaml $v.resources | nindent 12 }}\n"
    if s.volumes.nonEmpty then
      sb ++= "      volumes:\n"
      for v <- s.volumes do
        sb ++= s"        - name: ${v.name}\n"
        sb ++= s"          persistentVolumeClaim:\n            claimName: {{ .Release.Name }}-${s.name}-${v.name}\n"
    sb.result()

  /** what the old single-service chart annotated a pod with, kept:
   * Prometheus scrapes by annotation and a service that publishes
   * metrics nobody scrapes is a service that has none */
  private def metrics(s: Service): String =
    (s.metricsPath, s.mainPort) match
      case (Some(path), Some(port)) =>
        s"""      annotations:
           |        prometheus.io/scrape: "true"
           |        prometheus.io/port: "$port"
           |        prometheus.io/path: ${quote(path)}
           |""".stripMargin
      case _ => ""

  private def configMap(s: Service): String =
    val sb = new StringBuilder
    sb ++= s"# generated by okay-deploy — edit the Deployment value, not this file\n"
    sb ++= s"""apiVersion: v1
              |kind: ConfigMap
              |metadata:
              |  name: {{ .Release.Name }}-${s.name}
              |data:
              |""".stripMargin
    for (k, v) <- s.settings.env do sb ++= s"  $k: ${quote(v)}\n"
    // one URL, built where the engine is known -- the same rule the
    // laptop target follows, with the cluster's own DNS names
    for db <- s.databases do
      val host = s"{{ .Release.Name }}-${s.name}-${db.as}"
      val url = db.engine match
        case Engine.Postgres => s"jdbc:postgresql://$host:${db.engine.port}/${db.database}"
        case Engine.Mongo => s"mongodb://$host:${db.engine.port}/${db.database}"
        case other => s"$host:${other.port}"
      sb ++= s"  ${Settings.envName("", s"${db.as}_url")}: ${quote(url)}\n"
    for c <- s.caches do
      sb ++= s"  ${Settings.envName("", s"${c.as}_url")}: " +
        s"${quote(s"{{ .Release.Name }}-${s.name}-${c.as}:${c.engine.port}")}\n"
    sb.result()

  private def service(s: Service): String =
    val sb = new StringBuilder
    sb ++= "# generated by okay-deploy — edit the Deployment value, not this file\n"
    sb ++= s"""apiVersion: v1
              |kind: Service
              |metadata:
              |  name: {{ .Release.Name }}-${s.name}
              |spec:
              |  type: ClusterIP
              |  selector:
              |    app.kubernetes.io/name: ${s.name}
              |    app.kubernetes.io/instance: {{ .Release.Name }}
              |  ports:
              |""".stripMargin
    for p <- s.ports do
      sb ++= s"    - name: ${if p.public then "http" else s"port-${p.number}"}\n"
      sb ++= s"      port: ${p.number}\n      targetPort: ${p.number}\n"
    sb.result()

  private def pvc(s: Service, v: Need.Volume): String =
    s"""{{- $$v := index .Values ${quote(s.name)} -}}
       |# generated by okay-deploy — edit the Deployment value, not this file
       |apiVersion: v1
       |kind: PersistentVolumeClaim
       |metadata:
       |  name: {{ .Release.Name }}-${s.name}-${v.name}
       |spec:
       |  accessModes:
       |    - ReadWriteOnce
       |  resources:
       |    requests:
       |      storage: {{ $$v.${v.name}Size }}
       |""".stripMargin

  private def ingress(s: Service): String =
    val sb = new StringBuilder
    sb ++= "# generated by okay-deploy — edit the Deployment value, not this file\n"
    sb ++= s"""apiVersion: networking.k8s.io/v1
              |kind: Ingress
              |metadata:
              |  name: {{ .Release.Name }}-${s.name}
              |""".stripMargin
    if s.tls.contains(TlsMode.Acme) then
      sb ++= "  annotations:\n"
      sb ++= "    # cert-manager issues and renews it; the ClusterIssuer is the\n"
      sb ++= "    # cluster's, not ours — set it with --set ingress.issuer=<name>\n"
      sb ++= "    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}\n"
    sb ++= "spec:\n  rules:\n"
    val port = s.mainPort.getOrElse(80)
    for host <- s.dns do
      sb ++= s"""    - host: ${quote(host)}
                |      http:
                |        paths:
                |          - path: /
                |            pathType: Prefix
                |            backend:
                |              service:
                |                name: {{ .Release.Name }}-${s.name}
                |                port:
                |                  number: $port
                |""".stripMargin
    s.tls match
      case Some(TlsMode.Acme) | Some(TlsMode.Files) =>
        sb ++= "  tls:\n    - hosts:\n"
        for host <- s.dns do sb ++= s"        - ${quote(host)}\n"
        sb ++= s"      secretName: {{ .Release.Name }}-${s.name}-tls\n"
      case _ =>
        // Proxy: the ingress IS the proxy, and terminating TLS is the
        // cluster's business rather than this chart's
        ()
    sb.result()

  private val devDatabaseWarning =
    """# ONE REPLICA, A PVC, AND NO BACKUPS. This is a development
      |# database: it survives a pod restart and nothing else — no
      |# failover, no point-in-time recovery, no upgrade path. For
      |# anything real, delete this file and point the service's
      |# *_URL setting at a managed instance.
      |""".stripMargin

  private def database(s: Service, db: Need.Database): String =
    val n = s"{{ .Release.Name }}-${s.name}-${db.as}"
    val sb = new StringBuilder
    sb ++= s"""{{- $$v := index .Values ${quote(s.name)} -}}
              |# generated by okay-deploy — edit the Deployment value, not this file
              |$devDatabaseWarning""".stripMargin
    sb ++= s"""apiVersion: v1
              |kind: Service
              |metadata:
              |  name: $n
              |spec:
              |  clusterIP: None
              |  selector:
              |    app.kubernetes.io/name: ${s.name}-${db.as}
              |    app.kubernetes.io/instance: {{ .Release.Name }}
              |  ports:
              |    - port: ${db.engine.port}
              |      targetPort: ${db.engine.port}
              |---
              |apiVersion: apps/v1
              |kind: StatefulSet
              |metadata:
              |  name: $n
              |spec:
              |  serviceName: $n
              |  replicas: 1
              |  selector:
              |    matchLabels:
              |      app.kubernetes.io/name: ${s.name}-${db.as}
              |      app.kubernetes.io/instance: {{ .Release.Name }}
              |  template:
              |    metadata:
              |      labels:
              |        app.kubernetes.io/name: ${s.name}-${db.as}
              |        app.kubernetes.io/instance: {{ .Release.Name }}
              |    spec:
              |      containers:
              |        - name: ${db.as}
              |          image: ${quote(db.engine.image(db.version))}
              |          ports:
              |            - containerPort: ${db.engine.port}
              |""".stripMargin
    val env = db.engine match
      case Engine.Postgres => Vector("POSTGRES_DB" -> db.database, "POSTGRES_USER" -> db.as)
      case Engine.Mongo => Vector("MONGO_INITDB_DATABASE" -> db.database)
      case _ => Vector.empty
    if env.nonEmpty || db.engine == Engine.Postgres then
      sb ++= "          env:\n"
      for (k, v) <- env do sb ++= s"            - name: $k\n              value: ${quote(v)}\n"
      if db.engine == Engine.Postgres then
        // the laptop target writes `local-only` here and says so; a
        // cluster does not, because a cluster is somebody's real one
        sb ++= "            - name: POSTGRES_PASSWORD\n"
        sb ++= "              valueFrom:\n                secretKeyRef:\n"
        sb ++= s"                  name: {{ .Release.Name }}-secrets\n"
        sb ++= s"                  key: ${passwordKey(s, db)}\n"
    sb ++= s"""          volumeMounts:
              |            - name: data
              |              mountPath: ${quote(dataDirOf(db.engine))}
              |  volumeClaimTemplates:
              |    - metadata:
              |        name: data
              |      spec:
              |        accessModes:
              |          - ReadWriteOnce
              |        resources:
              |          requests:
              |            storage: {{ $$v.${db.as}Size }}
              |""".stripMargin
    sb.result()

  private def cache(s: Service, c: Need.Cache): String =
    val n = s"{{ .Release.Name }}-${s.name}-${c.as}"
    s"""# generated by okay-deploy — edit the Deployment value, not this file
       |# A cache holds nothing that cannot be rebuilt, so this one has no
       |# volume: losing it costs a warm-up, not data.
       |apiVersion: v1
       |kind: Service
       |metadata:
       |  name: $n
       |spec:
       |  selector:
       |    app.kubernetes.io/name: ${s.name}-${c.as}
       |    app.kubernetes.io/instance: {{ .Release.Name }}
       |  ports:
       |    - port: ${c.engine.port}
       |      targetPort: ${c.engine.port}
       |---
       |apiVersion: apps/v1
       |kind: Deployment
       |metadata:
       |  name: $n
       |spec:
       |  replicas: 1
       |  selector:
       |    matchLabels:
       |      app.kubernetes.io/name: ${s.name}-${c.as}
       |      app.kubernetes.io/instance: {{ .Release.Name }}
       |  template:
       |    metadata:
       |      labels:
       |        app.kubernetes.io/name: ${s.name}-${c.as}
       |        app.kubernetes.io/instance: {{ .Release.Name }}
       |    spec:
       |      containers:
       |        - name: ${c.as}
       |          image: ${quote(c.engine.image(c.version))}
       |          ports:
       |            - containerPort: ${c.engine.port}
       |""".stripMargin

  // ---- the Secret this chart does NOT own ---------------------------

  private[deploy] def passwordKey(s: Service, db: Need.Database): String =
    Settings.envName("", s"${s.name}_${db.as}_password")

  /** every key the chart reads out of `<release>-secrets`, and the
   * command that creates it. NOT a template: `helm upgrade` would
   * overwrite the operator's real Secret with blanks, and the first
   * symptom is every pod crash-looping with an empty password. */
  def keys(d: Deployment): Vector[(String, String)] =
    d.services.flatMap { s =>
      s.secrets.flatMap(sec => Targets.envVarOf(sec).map(_ -> s"${s.name} reads it as ${sec.ref}")) ++
        s.databases.filter(_.engine == Engine.Postgres)
          .map(db => passwordKey(s, db) -> s"the password for the ${db.engine} beside ${s.name} (${db.database})")
    }.distinctBy(_._1)

  private def secretsScript(d: Deployment): String =
    val ks = keys(d)
    val sb = new StringBuilder
    sb ++= s"""#!/bin/sh
              |# generated by okay-deploy from ${d.name}'s Deployment value
              |#
              |# The chart REFERENCES this Secret and does not own it, on purpose:
              |# a templated Secret would be overwritten with blanks by the next
              |# `helm upgrade`, and the first symptom is every pod crash-looping
              |# at 3am. So it is created once, here, by you.
              |#
              |# No value is in this file, and none ever will be — fill them in
              |# where you run it, from your own vault.
              |set -e
              |RELEASE=$${RELEASE:-${d.name}}
              |NAMESPACE=$${NAMESPACE:-default}
              |""".stripMargin
    if ks.isEmpty then
      sb ++= "\n# this deployment reads no secrets; nothing to create.\n"
    else
      sb ++= "\nkubectl create secret generic \"$RELEASE-secrets\" \\\n"
      sb ++= "  --namespace \"$NAMESPACE\" \\\n"
      for (k, why) <- ks do
        sb ++= s"""  --from-literal=$k="$${$k:?set $k — ${Shell.prompt(why)}}" \\\n"""
      sb ++= "  --dry-run=client -o yaml | kubectl apply -f -\n"
    sb.result()

  // ---- shared -------------------------------------------------------

  private def quote(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  private def dataDirOf(e: Engine): String = e match
    case Engine.Postgres => "/var/lib/postgresql/data"
    case Engine.Mongo => "/data/db"
    case Engine.Redis => "/data"
    case Engine.Kafka => "/bitnami/kafka"
