package okay.deploy

import okay.codec.Schema
import java.nio.file.{Files, Path}

/**
 * What survived specs/deploy.md.
 *
 * `Deploy` — one process, its Dockerfile, its compose file and its
 * single-service Helm chart — was superseded by `Deployment` on
 * 2026-09-07 (deploy-old-helm-retired) once the new model had six
 * targets and okay-script was committing two charts for one
 * application. These four types outlived it because they were right:
 * they say what an image copies, how long a start may take, what a
 * pod may use, and where the repository root is.
 */
final case class Resources(cpuRequest: String, memoryRequest: String, cpuLimit: String, memoryLimit: String)

/**
 * The probes a target wires, how long a start may take before one is
 * believed, and how long a STOP may take before the platform kills.
 *
 * `stopSeconds` is the drain's budget (deploy-stop-grace): okay-ops's
 * `Signals.awaitSignal` answers SIGTERM by turning readiness off,
 * waiting for endpoint removal to propagate, and letting in-flight
 * requests finish — 2 + 15 s by default. A platform that kills before
 * that has a drain in name only, and every platform's default is at
 * or under it (Kubernetes 30, compose 10, ECS 30). 30 is the default
 * here because it clears 17 with room, and it is rendered wherever the
 * target has a documented equivalent. No `preStop` hook anywhere: the
 * process handles the signal itself.
 */
final case class Health(livenessPath: String = "/healthz", readinessPath: String = "/readyz",
                        startupSeconds: Int = 30, stopSeconds: Int = 30)

/** one `COPY --from=build <from> <to>` line — `from` a glob in the
 * build stage, `to` a path in the final image */
final case class Copy(from: String, to: String)

object Deploy:
  given Schema[Copy] = Schema.derived
  given Schema[Resources] = Schema.derived
  given Schema[Health] = Schema.derived

  /** the repository root: the nearest ancestor of `from` holding a
   * build.sbt — a rendered path is relative to it, whatever cwd a
   * forked `run` or test happens to have */
  def repoRoot(from: Path = Path.of(".").toAbsolutePath.normalize): Path =
    Iterator.iterate(from)(_.getParent).takeWhile(_ != null)
      .find(p => Files.exists(p.resolve("build.sbt")))
      .getOrElse(throw IllegalStateException(s"no build.sbt above $from"))

/**
 * The multi-stage build every target's image comes out of: an sbt
 * image builds ONE module's fat jar (`OkayDeploy.deployable` fixed
 * its name), a slim JRE runs it.
 *
 * It renders from a `Service` rather than a whole `Deployment`
 * because an image is one service's, and a system of three
 * module-built services is three images.
 */
object Dockerfile:
  val sbtImage = "sbtscala/scala-sbt:eclipse-temurin-21.0.5_11_1.10.7_3.5.2"
  val jreImage = "eclipse-temurin:21-jre-alpine"

  def render(d: Deployment, s: Service, m: Run.Module): String =
    val tasks = (Vector(s"${m.module}/assembly") ++ m.extraBuild)
      .map(t => s"\"$t\"").mkString(" ")
    val extraCopyLines = m.extraCopy
      .map(c => s"COPY --from=build /src/${c.from} ${c.to}\n").mkString
    val expose = s.mainPort.map(p => s"EXPOSE $p\n").getOrElse("")
    s"""# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file
       |FROM $sbtImage AS build
       |WORKDIR /src
       |COPY project project
       |COPY build.sbt .
       |RUN sbt update
       |COPY . .
       |RUN sbt $tasks
       |
       |FROM $jreImage
       |RUN addgroup -S okay && adduser -S okay -G okay
       |COPY --from=build /src/${m.moduleDir}/target/scala-*/app.jar /app/app.jar
       |${extraCopyLines}USER okay
       |WORKDIR /app
       |$expose""".stripMargin +
      s"""ENTRYPOINT ["sh", "-c", "exec java ${m.javaOpts} -jar /app/app.jar"]
         |""".stripMargin

private object Yaml:
  /** a double-quoted YAML scalar — every value quoted, so ":memory:",
   * "8080" and "true" all stay the strings they are */
  def str(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
