package okay.deploy

import java.nio.file.Path

/**
 * Google Cloud, as Terraform for Cloud Run (specs/deployment.md,
 * stage 3).
 *
 * The same shape as `aws` and the same gate. What is different is
 * where the platform is, and one place where it is NOT: a
 * `Need.Volume` is REFUSED here. Cloud Run can mount a GCS bucket
 * through gcsfuse, and that is object storage wearing a filesystem —
 * no atomic rename, no locking — which is exactly what okay-persist's
 * log is built on. A deployment that mounted one would work in a demo
 * and corrupt a log under concurrency.
 */
object Gcp extends Target:
  val name = "gcp"

  def requires(d: Deployment): Vector[String] = Vector("terraform", "gcloud")

  def up(dir: Path): Vector[String] = Vector("terraform", s"-chdir=${dir.toString}", "apply")
  def down(dir: Path): Vector[String] = Vector("terraform", s"-chdir=${dir.toString}", "destroy")

  def render(d: Deployment): Either[String, Vector[(String, String)]] =
    val noRegion = d.services.filter(_.region.isEmpty).map(_.name)
    val volumes = d.services.filter(_.volumes.nonEmpty).map(_.name)
    if noRegion.nonEmpty then
      Left(s"gcp needs a region for ${noRegion.mkString(", ")} and no target can invent one — " +
        "add Need.Region(\"europe-west1\") (or wherever your users are)")
    else if volumes.nonEmpty then
      Left(s"${volumes.mkString(", ")} needs a durable directory and Cloud Run has none — " +
        "the bucket it can mount is object storage through gcsfuse, with no atomic rename and no " +
        "locking, and okay-persist's log needs both. Use the `cluster` target on GKE, which has real " +
        "persistent disks, or point the service at a database instead of a directory")
    else d.ordered.map { services =>
      Vector(
        "main.tf" -> Aws.align(main(d, services)),
        "setup.sh" -> setup(d, services)) ++
        services.map(s => s"${s.name}.tf" -> Aws.align(serviceTf(d, s))) ++
        d.extra.filter(_.target == name).map(e => e.path -> e.content)
    }

  // ------------------------------------------------------------------

  private def main(d: Deployment, services: Vector[Service]): String =
    val region = services.headOption.flatMap(_.region).getOrElse("")
    val sb = new StringBuilder
    sb ++= s"""# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file
              |#
              |# THE PROJECT IS NOT OURS. `project` has no default: a Google
              |# project is a billing boundary and an IAM boundary, and no
              |# deployment renderer should pick one for you.
              |
              |terraform {
              |  required_version = ">= 1.5"
              |  required_providers {
              |    google = {
              |      source  = "hashicorp/google"
              |      version = "~> 6.0"
              |    }
              |  }
              |}
              |
              |provider "google" {
              |  project = var.project
              |  region  = var.region
              |}
              |
              |variable "project" {
              |  description = "the Google project this runs in — a billing and IAM boundary, so it has no default"
              |  type        = string
              |}
              |
              |variable "region" {
              |  description = "where this runs"
              |  type        = string
              |  default     = ${str(region)}
              |}
              |
              |# the identity the services run AS — not the one that deploys
              |# them, which is yours
              |resource "google_service_account" "run" {
              |  account_id   = ${str(s"${d.name}-run".take(30))}
              |  display_name = ${str(s"${d.name} services")}
              |}
              |""".stripMargin
    if services.exists(_.databases.nonEmpty) then
      sb ++= s"""
                |# a private address for the databases below, so nothing is
                |# reachable from the internet that does not have to be
                |resource "google_compute_global_address" "private" {
                |  name          = ${str(s"${d.name}-private")}
                |  purpose       = "VPC_PEERING"
                |  address_type  = "INTERNAL"
                |  prefix_length = 16
                |  network       = "default"
                |}
                |
                |resource "google_service_networking_connection" "private" {
                |  network                 = "projects/$${var.project}/global/networks/default"
                |  service                 = "servicenetworking.googleapis.com"
                |  reserved_peering_ranges = [google_compute_global_address.private.name]
                |}
                |""".stripMargin
    sb.result()

  private def serviceTf(d: Deployment, s: Service): String =
    val r = ref(s.name)
    val full = s"${d.name}-${s.name}"
    val sb = new StringBuilder
    sb ++= "# generated by okay-deploy — edit the Deployment value, not this file\n\n"

    for name <- Aws.secretsOf(s) do
      sb ++= s"""# created OUT OF BAND by setup.sh: `terraform apply` writes every
                |# attribute into the state file, and a secret VERSION would put
                |# the value there in plaintext
                |data "google_secret_manager_secret" ${str(ref(name))} {
                |  secret_id = ${str(s"$full-$name")}
                |}
                |
                |resource "google_secret_manager_secret_iam_member" ${str(ref(name))} {
                |  secret_id = data.google_secret_manager_secret.${ref(name)}.id
                |  role      = "roles/secretmanager.secretAccessor"
                |  member    = "serviceAccount:$${google_service_account.run.email}"
                |}
                |
                |""".stripMargin

    for db <- s.databases do
      val dr = s"${r}_${ref(db.as)}"
      sb ++= s"""data "google_secret_manager_secret_version" ${str(s"${dr}_password")} {
                |  secret = ${str(s"$full-${Aws.passwordName(db)}")}
                |}
                |
                |resource "google_sql_database_instance" ${str(dr)} {
                |  name             = ${str(s"$full-${db.as}")}
                |  database_version = ${str(sqlVersion(db))}
                |  region           = var.region
                |
                |  # a managed database is the one thing here you cannot
                |  # re-create from this file: turn these on before you rely on it
                |  deletion_protection = false
                |
                |  settings {
                |    tier = "db-f1-micro"
                |
                |    backup_configuration {
                |      enabled = true
                |    }
                |
                |    ip_configuration {
                |      ipv4_enabled    = false
                |      private_network = "projects/$${var.project}/global/networks/default"
                |    }
                |  }
                |
                |  depends_on = [google_service_networking_connection.private]
                |}
                |
                |resource "google_sql_database" ${str(dr)} {
                |  name     = ${str(db.database)}
                |  instance = google_sql_database_instance.$dr.name
                |}
                |
                |resource "google_sql_user" ${str(dr)} {
                |  name     = ${str(db.as)}
                |  instance = google_sql_database_instance.$dr.name
                |  password = data.google_secret_manager_secret_version.${dr}_password.secret_data
                |}
                |
                |""".stripMargin

    for c <- s.caches do
      val cr = s"${r}_${ref(c.as)}"
      sb ++= s"""resource "google_redis_instance" ${str(cr)} {
                |  name           = ${str(s"$full-${c.as}")}
                |  tier           = "BASIC"
                |  memory_size_gb = 1
                |  region         = var.region
                |}
                |
                |""".stripMargin

    sb ++= s"""resource "google_cloud_run_v2_service" ${str(r)} {
              |  name     = ${str(full)}
              |  location = var.region
              |
              |  # Cloud Run is public by a flag, and its own name has a
              |  # managed certificate from the moment it exists
              |  ingress = ${if s.ports.exists(_.public) then "\"INGRESS_TRAFFIC_ALL\"" else "\"INGRESS_TRAFFIC_INTERNAL_ONLY\""}
              |
              |  template {
              |    service_account = google_service_account.run.email
              |
              |    scaling {
              |      min_instance_count = ${s.scale.replicas}
              |    }
              |
              |    containers {
              |      image = ${str(imageOf(d, s))}
              |""".stripMargin
    s.mainPort.foreach { port =>
      sb ++= s"""
                |      ports {
                |        container_port = $port
                |      }
                |""".stripMargin
    }
    for (k, v) <- s.settings.env ++ databaseEnv(s, r) do
      sb ++= s"""
                |      env {
                |        name  = ${str(k)}
                |        value = ${str(v)}
                |      }
                |""".stripMargin
    for n <- Aws.secretsOf(s) do
      sb ++= s"""
                |      env {
                |        name = ${str(n)}
                |
                |        value_source {
                |          secret_key_ref {
                |            secret  = data.google_secret_manager_secret.${ref(n)}.secret_id
                |            version = "latest"
                |          }
                |        }
                |      }
                |""".stripMargin
    s.resources.foreach { res =>
      sb ++= s"""
                |      resources {
                |        limits = {
                |          cpu    = ${str(res.cpuLimit)}
                |          memory = ${str(res.memoryLimit.replace("Mi", "Mi").replace("Gi", "Gi"))}
                |        }
                |      }
                |""".stripMargin
    }
    s.mainPort.foreach { port =>
      sb ++= s"""
                |      startup_probe {
                |        http_get {
                |          path = ${str(s.health.livenessPath)}
                |          port = $port
                |        }
                |
                |        period_seconds    = 5
                |        failure_threshold = ${math.max(1, s.health.startupSeconds / 5)}
                |      }
                |
                |      liveness_probe {
                |        http_get {
                |          path = ${str(s.health.livenessPath)}
                |          port = $port
                |        }
                |
                |        period_seconds = 10
                |      }
                |""".stripMargin
    }
    sb ++= """    }
             |  }
             |}
             |""".stripMargin

    if s.ports.exists(_.public) then
      sb ++= s"""
                |# public, because the value said the port was
                |resource "google_cloud_run_v2_service_iam_member" ${str(r)} {
                |  name     = google_cloud_run_v2_service.$r.name
                |  location = google_cloud_run_v2_service.$r.location
                |  role     = "roles/run.invoker"
                |  member   = "allUsers"
                |}
                |
                |output "${r}_url" {
                |  description = "the platform's own name, with a managed certificate from the moment it exists"
                |  value       = google_cloud_run_v2_service.$r.uri
                |}
                |""".stripMargin

    for (host, i) <- s.dns.zipWithIndex do
      sb ++= s"""
                |# A CUSTOM DOMAIN NEEDS VERIFICATION FIRST: a TXT record
                |# proving you own $host, checked by Google, before a
                |# certificate is issued. No Terraform resource does that for
                |# you — run `gcloud domains verify $host` and then apply.
                |resource "google_cloud_run_domain_mapping" ${str(s"${r}_domain_$i")} {
                |  name     = ${str(host)}
                |  location = var.region
                |
                |  metadata {
                |    namespace = var.project
                |  }
                |
                |  spec {
                |    route_name = google_cloud_run_v2_service.$r.name
                |  }
                |}
                |""".stripMargin
    sb.result()

  // ------------------------------------------------------------------

  private def setup(d: Deployment, services: Vector[Service]): String =
    val sb = new StringBuilder
    sb ++= s"""#!/bin/sh
              |# generated by okay-deploy from ${d.name}'s Deployment value
              |#
              |# Every secret this deployment reads, created BEFORE terraform runs.
              |#
              |# Why here and not in a .tf file: `terraform apply` writes every
              |# resource attribute into the state file, and a secret version
              |# would put the VALUE there in plaintext.
              |#
              |# No value is in this file and none ever will be.
              |set -e
              |PROJECT=$${GOOGLE_PROJECT:?set GOOGLE_PROJECT to the project this deploys into}
              |
              |create() { # name, value
              |  gcloud secrets create "$$1" --project "$$PROJECT" --replication-policy=automatic >/dev/null 2>&1 || true
              |  printf '%s' "$$2" | gcloud secrets versions add "$$1" --project "$$PROJECT" --data-file=- >/dev/null
              |  echo "  $$1"
              |}
              |
              |""".stripMargin
    var any = false
    for s <- services do
      val full = s"${d.name}-${s.name}"
      val names = Aws.secretsOf(s).map(n => n -> s"read by ${s.name} as $n") ++
        s.databases.map(db => Aws.passwordName(db) -> s"the password for the ${db.engine} beside ${s.name}")
      if names.nonEmpty then
        any = true
        sb ++= s"echo ${q(s"${s.name}:")}\n"
        for (n, why) <- names do
          sb ++= s"""create ${q(s"$full-$n")} "$${$n:?set $n in your own environment — ${Shell.prompt(why)}}"\n"""
        sb ++= "\n"
    if !any then sb ++= "echo 'this deployment reads no secrets; nothing to create.'\n"
    sb.result()

  private def imageOf(d: Deployment, s: Service): String = s.run match
    case Run.Image(repo, tag) => s"$repo:$tag"
    case _: Run.Module => s"gcr.io/PROJECT/${d.name}-${s.name}:latest"

  private def databaseEnv(s: Service, r: String): Vector[(String, String)] =
    s.databases.map { db =>
      val dr = s"${r}_${ref(db.as)}"
      val host = s"$${google_sql_database_instance.$dr.private_ip_address}"
      val url = db.engine match
        case Engine.Postgres => s"jdbc:postgresql://$host:${db.engine.port}/${db.database}"
        case Engine.Mongo => s"mongodb://$host:${db.engine.port}/${db.database}"
        case _ => host
      Settings.envName("", s"${db.as}_url") -> url
    } ++ s.caches.map { c =>
      val cr = s"${r}_${ref(c.as)}"
      Settings.envName("", s"${c.as}_url") ->
        s"$${google_redis_instance.$cr.host}:$${google_redis_instance.$cr.port}"
    }

  private def sqlVersion(db: Need.Database): String = db.engine match
    case Engine.Postgres => "POSTGRES_" + db.version.takeWhile(_ != '.')
    case other => other.toString.toUpperCase

  private def ref(s: String): String =
    val cleaned = s.map(c => if c.isLetterOrDigit then c else '_')
    if cleaned.headOption.exists(_.isDigit) then s"_$cleaned" else cleaned

  private def str(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
  private def q(s: String): String = "'" + s.replace("'", "'\\''") + "'"
