package okay.deploy

import java.nio.file.Path

/**
 * The three platforms that take a repository and run it
 * (specs/deployment.md, stage 2).
 *
 * They disagree about what a deployment IS, and the renderers show
 * it: fly is one app per file, render takes the whole system in one
 * Blueprint, railway is per-service JSON. None can be applied without
 * an account, so `up` is the platform's own CLI and the gate stops at
 * the rendering — with a real parser per format, because stage 1
 * demonstrated that a golden file passes happily on output the
 * consuming tool rejects.
 *
 * A managed database is DELEGATED here rather than refused: the
 * platform has one, the FILE cannot express it, so `setup.sh` carries
 * the exact commands. Render is the exception — a Blueprint has a
 * `databases:` section, so there it is in the file.
 */
object Paas:

  // ---- fly.io -------------------------------------------------------

  /**
   * One app per `fly.toml`, which is the whole shape of this target:
   * a system of three services is three apps, three directories and
   * three files, and `up` is three deploys.
   */
  object Fly extends Target:
    val name = "fly"

    def requires(d: Deployment): Vector[String] = Vector("flyctl")

    /** one deploy per app: `up` runs the first, and `setup.sh` lists
     * them all — a target that pretended one command deploys three
     * apps would be lying about what it did */
    def up(dir: Path): Vector[String] = Vector("sh", dir.resolve("deploy.sh").toString)
    def down(dir: Path): Vector[String] = Vector("sh", dir.resolve("destroy.sh").toString)

    def render(d: Deployment): Either[String, Vector[(String, String)]] =
      val noRegion = d.services.filter(_.region.isEmpty).map(_.name)
      if noRegion.nonEmpty then
        Left(s"fly needs a primary region for ${noRegion.mkString(", ")} and no target can invent one — " +
          "add Need.Region(\"iad\") (or the code of a region near your users: `flyctl platform regions`)")
      else d.ordered.map { services =>
        services.map(s => s"${s.name}/fly.toml" -> flyToml(d, s)) ++
          Vector(
            "setup.sh" -> flySetup(d, services),
            "deploy.sh" -> flyScript(d, services, "deploy", "flyctl deploy --config \"$here/%s/fly.toml\" --app \"%s\""),
            "destroy.sh" -> flyScript(d, services, "destroy", "flyctl apps destroy \"%2$s\" --yes")) ++
          d.extra.filter(_.target == name).map(e => e.path -> e.content)
      }

    private def appOf(d: Deployment, s: Service): String =
      if d.services.length == 1 then d.name else s"${d.name}-${s.name}"

    private def flyToml(d: Deployment, s: Service): String =
      val sb = new StringBuilder
      sb ++= s"# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file\n"
      sb ++= s"app = ${str(appOf(d, s))}\n"
      sb ++= s"primary_region = ${str(s.region.getOrElse(""))}\n\n"
      s.run match
        case Run.Image(repo, tag) =>
          sb ++= s"[build]\n  image = ${str(s"$repo:$tag")}\n\n"
        case Run.Module(_, moduleDir, _, _) =>
          sb ++= s"[build]\n  dockerfile = ${str(s"../../../$moduleDir/deploy/Dockerfile")}\n\n"
      if s.settings.all.nonEmpty then
        sb ++= "[env]\n"
        for (k, v) <- s.settings.env do sb ++= s"  $k = ${str(v)}\n"
        sb ++= "\n"
      s.mainPort match
        case None =>
          // no port is a worker: fly runs it with no http service at
          // all, which is a different app shape rather than a gap
          sb ++= "# no port: this app is a worker and fly gives it no public address\n\n"
        case Some(port) =>
          sb ++= s"""[http_service]
                    |  internal_port = $port
                    |  force_https = ${s.tls.forall(_ != TlsMode.None)}
                    |  auto_stop_machines = "suspend"
                    |  auto_start_machines = true
                    |  min_machines_running = ${s.scale.replicas}
                    |
                    |[[http_service.checks]]
                    |  grace_period = "${s.health.startupSeconds}s"
                    |  interval = "10s"
                    |  method = "GET"
                    |  timeout = "2s"
                    |  path = ${str(s.health.livenessPath)}
                    |
                    |""".stripMargin
      for v <- s.volumes do
        sb ++= s"""[[mounts]]
                  |  source = ${str(s"${s.name.replace('-', '_')}_${v.name}")}
                  |  destination = ${str(v.path)}
                  |  initial_size = ${str(v.size.toLowerCase.replace("gi", "gb"))}
                  |
                  |""".stripMargin
      s.resources.foreach { r =>
        sb ++= s"""[[vm]]
                  |  memory = ${str(r.memoryLimit.toLowerCase.replace("mi", "mb").replace("gi", "gb"))}
                  |  cpu_kind = "shared"
                  |  cpus = 1
                  |
                  |""".stripMargin
      }
      sb.result()

    private def flySetup(d: Deployment, services: Vector[Service]): String =
      val sb = new StringBuilder
      sb ++= s"""#!/bin/sh
                |# generated by okay-deploy from ${d.name}'s Deployment value
                |#
                |# Everything fly.toml cannot say. Run this ONCE, then deploy.sh.
                |# No secret value is in this file and none ever will be.
                |set -e
                |""".stripMargin
      for s <- services do
        val app = appOf(d, s)
        sb ++= s"\n# ---- ${s.name} → app $app\n"
        sb ++= s"flyctl apps create ${q(app)} || echo ${q(s"app $app already exists")}\n"
        for v <- s.volumes do
          sb ++= s"flyctl volumes create ${q(s"${s.name.replace('-', '_')}_${v.name}")} " +
            s"--app ${q(app)} --region ${q(s.region.getOrElse(""))} --size ${v.size.toLowerCase.filter(_.isDigit)}\n"
        for db <- s.databases do
          // the FILE cannot express this; the platform can. So the
          // command is here, exactly, rather than guessed into a toml
          sb ++= s"# ${s.name} needs a ${db.engine}: fly runs it as a SEPARATE app, and `attach`\n"
          sb ++= s"# is what sets DATABASE_URL — neither is expressible in fly.toml\n"
          sb ++= s"flyctl postgres create --name ${q(s"$app-${db.as}")} --region ${q(s.region.getOrElse(""))}\n"
          sb ++= s"flyctl postgres attach ${q(s"$app-${db.as}")} --app ${q(app)}\n"
        for c <- s.caches do
          sb ++= s"# ${s.name} needs a ${c.engine}: `flyctl redis create` is a managed Upstash instance\n"
          sb ++= s"flyctl redis create --name ${q(s"$app-${c.as}")}\n"
        val vars = s.secrets.flatMap(Targets.envVarOf)
        if vars.nonEmpty then
          sb ++= s"flyctl secrets set --app ${q(app)} \\\n"
          for v <- vars do sb ++= s"""  $v="$${$v:?set $v in your own environment first}" \\\n"""
          sb ++= "  --stage\n"
        for host <- s.dns do
          sb ++= s"flyctl certs create ${q(host)} --app ${q(app)}\n"
      sb.result()

    private def flyScript(d: Deployment, services: Vector[Service], what: String, line: String): String =
      val sb = new StringBuilder
      sb ++= s"""#!/bin/sh
                |# generated by okay-deploy from ${d.name}'s Deployment value
                |# $what every app this deployment is, in order.
                |set -e
                |here=$$(CDPATH= cd -- "$$(dirname -- "$$0")" && pwd)
                |""".stripMargin
      for s <- services do
        sb ++= line.format(s.name, appOf(d, s)) + "\n"
      sb.result()

  // ---- render.com ---------------------------------------------------

  /**
   * A Blueprint: one `render.yaml` for the whole system, databases
   * included — the closest of the three to the shape of our value,
   * and the one place a `Need.Database` is IN the file.
   */
  object Render extends Target:
    val name = "render"

    def requires(d: Deployment): Vector[String] = Vector.empty

    // Render applies a Blueprint from the repository, not from a
    // laptop: there is no `render up`, and saying so is better than
    // inventing a command that does not exist
    def up(dir: Path): Vector[String] =
      Vector("echo", "Render applies render.yaml from your git repository — " +
        "commit it and press Apply in the dashboard (Blueprints -> New Blueprint Instance)")
    def down(dir: Path): Vector[String] =
      Vector("echo", "delete the Blueprint instance in the Render dashboard; there is no CLI for it")

    def render(d: Deployment): Either[String, Vector[(String, String)]] =
      d.ordered.map { services =>
        val sb = new StringBuilder
        sb ++= s"# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file\n"
        sb ++= "services:\n"
        for s <- services do
          sb ++= s"  - type: ${if s.mainPort.isDefined then "web" else "worker"}\n"
          sb ++= s"    name: ${s.name}\n"
          sb ++= "    runtime: docker\n"
          s.run match
            case Run.Image(repo, tag) =>
              sb ++= s"    image:\n      url: ${y(s"$repo:$tag")}\n"
            case Run.Module(_, moduleDir, _, _) =>
              sb ++= s"    dockerfilePath: ${y(s"./$moduleDir/deploy/Dockerfile")}\n"
              sb ++= "    dockerContext: .\n"
          s.region.foreach(r => sb ++= s"    region: ${y(r)}\n")
          sb ++= s"    plan: starter\n"
          if s.scale.replicas > 1 then sb ++= s"    numInstances: ${s.scale.replicas}\n"
          s.mainPort.foreach(_ => sb ++= s"    healthCheckPath: ${y(s.health.readinessPath)}\n")
          val vars = s.settings.env ++
            s.mainPort.map("PORT" -> _.toString) ++
            s.databases.map(db => Settings.envName("", s"${db.as}_url") -> "")
          if vars.nonEmpty || s.secrets.nonEmpty then
            sb ++= "    envVars:\n"
            for (k, v) <- s.settings.env do sb ++= s"      - key: $k\n        value: ${y(v)}\n"
            s.mainPort.foreach(p => sb ++= s"      - key: PORT\n        value: ${y(p.toString)}\n")
            for db <- s.databases do
              sb ++= s"      - key: ${Settings.envName("", s"${db.as}_url")}\n"
              sb ++= s"        fromDatabase:\n          name: ${s.name}-${db.as}\n          property: connectionString\n"
            // sync: false is Render's way of saying "a human types
            // this in the dashboard" -- a REFERENCE, never a value
            for sec <- s.secrets; v <- Targets.envVarOf(sec) do
              sb ++= s"      - key: $v\n        sync: false\n"
          for v <- s.volumes do
            sb ++= s"""    disk:
                      |      name: ${v.name}
                      |      mountPath: ${y(v.path)}
                      |      sizeGB: ${v.size.toLowerCase.filter(_.isDigit)}
                      |""".stripMargin
        val databases = services.flatMap(s => s.databases.map(s -> _))
        val unsupported = services.flatMap(s => s.caches.map(c => s"${s.name} needs a ${c.engine}"))
        if databases.nonEmpty then
          sb ++= "\ndatabases:\n"
          for (s, db) <- databases do
            if db.engine != Engine.Postgres then
              sb ++= s"  # ${db.engine} is not a managed Render database; run it as a private service\n"
            sb ++= s"  - name: ${s.name}-${db.as}\n"
            sb ++= s"    databaseName: ${y(db.database)}\n"
            sb ++= s"    plan: basic-256mb\n"
            s.region.foreach(r => sb ++= s"    region: ${y(r)}\n")
        val notes =
          if unsupported.isEmpty then ""
          else "\n# NOT in this file, because a Blueprint cannot say it:\n" +
            unsupported.map(u => s"#   $u — add a Render Key Value instance in the dashboard\n").mkString
        Vector("render.yaml" -> (sb.result() + notes)) ++
          d.extra.filter(_.target == name).map(e => e.path -> e.content)
      }

  // ---- railway.app --------------------------------------------------

  /**
   * Per-service JSON. The project itself is made in the dashboard or
   * by the CLI, so what is rendered here is only what a service's
   * build and deploy look like — and `setup.sh` is the rest.
   */
  object Railway extends Target:
    val name = "railway"

    def requires(d: Deployment): Vector[String] = Vector("railway")

    def up(dir: Path): Vector[String] = Vector("sh", dir.resolve("deploy.sh").toString)
    def down(dir: Path): Vector[String] =
      Vector("echo", "delete the environment in the Railway dashboard; `railway down` removes only the latest deployment")

    def render(d: Deployment): Either[String, Vector[(String, String)]] =
      d.ordered.map { services =>
        services.map(s => s"${s.name}/railway.json" -> railwayJson(s)) ++
          Vector("setup.sh" -> railwaySetup(d, services), "deploy.sh" -> railwayDeploy(d, services)) ++
          d.extra.filter(_.target == name).map(e => e.path -> e.content)
      }

    private def railwayJson(s: Service): String =
      import okay.codec.Json
      val build = s.run match
        case Run.Image(repo, tag) => Vector("builder" -> Json.JStr("DOCKERFILE"),
          "dockerfilePath" -> Json.JStr(s"# image $repo:$tag is set on the service, not here"))
        case Run.Module(_, moduleDir, _, _) => Vector(
          "builder" -> Json.JStr("DOCKERFILE"),
          "dockerfilePath" -> Json.JStr(s"$moduleDir/deploy/Dockerfile"))
      val deploy = Vector(
        "numReplicas" -> Json.JNum(s.scale.replicas.toDouble),
        "restartPolicyType" -> Json.JStr("ON_FAILURE"),
        "restartPolicyMaxRetries" -> Json.JNum(10)) ++
        s.mainPort.map(_ => "healthcheckPath" -> Json.JStr(s.health.readinessPath)) ++
        s.mainPort.map(_ => "healthcheckTimeout" -> Json.JNum(s.health.startupSeconds.toDouble)) ++
        s.region.map(r => "region" -> Json.JStr(r))
      // indented, because this one is COMMITTED and read by people;
      // okay-codec's printer is compact by design (it is a wire
      // format), so the indenting belongs here rather than there
      pretty(Json.JObj(Vector(
        "$schema" -> Json.JStr("https://railway.com/railway.schema.json"),
        "build" -> Json.JObj(build),
        "deploy" -> Json.JObj(deploy))), 0) + "\n"

    private def railwaySetup(d: Deployment, services: Vector[Service]): String =
      val sb = new StringBuilder
      sb ++= s"""#!/bin/sh
                |# generated by okay-deploy from ${d.name}'s Deployment value
                |#
                |# Everything railway.json cannot say: the project, the services,
                |# the managed engines and the variables. Run this ONCE.
                |# No secret value is in this file and none ever will be.
                |set -e
                |railway init --name ${q(d.name)} || echo ${q("project exists; `railway link` it instead")}
                |""".stripMargin
      for s <- services do
        sb ++= s"\n# ---- ${s.name}\n"
        sb ++= s"railway add --service ${q(s.name)}\n"
        for db <- s.databases do
          sb ++= s"# ${s.name} needs a ${db.engine}: railway runs it as a managed plugin,\n"
          sb ++= s"# and the connection URL arrives as a reference variable\n"
          sb ++= s"railway add --database ${q(db.engine.toString.toLowerCase)}\n"
          sb ++= s"railway variables --service ${q(s.name)} " +
            s"--set ${q(s"${Settings.envName("", s"${db.as}_url")}=" + "${{Postgres.DATABASE_URL}}")}\n"
        for c <- s.caches do
          sb ++= s"railway add --database ${q(c.engine.toString.toLowerCase)}\n"
        val settings = s.settings.env ++ s.mainPort.map("PORT" -> _.toString)
        if settings.nonEmpty then
          sb ++= s"railway variables --service ${q(s.name)} \\\n"
          for (k, v) <- settings do sb ++= s"  --set ${q(s"$k=$v")} \\\n"
          sb ++= "  --skip-deploys\n"
        val vars = s.secrets.flatMap(Targets.envVarOf)
        if vars.nonEmpty then
          sb ++= s"railway variables --service ${q(s.name)} \\\n"
          for v <- vars do sb ++= s"""  --set "$v=$${$v:?set $v in your own environment first}" \\\n"""
          sb ++= "  --skip-deploys\n"
        if s.volumes.nonEmpty then
          sb ++= s"# railway volumes are made in the dashboard: Service -> Settings -> Volumes\n"
          for v <- s.volumes do sb ++= s"#   ${s.name}: mount ${v.path} (${v.size})\n"
      sb.result()

    private def railwayDeploy(d: Deployment, services: Vector[Service]): String =
      val sb = new StringBuilder
      sb ++= s"""#!/bin/sh
                |# generated by okay-deploy from ${d.name}'s Deployment value
                |set -e
                |here=$$(CDPATH= cd -- "$$(dirname -- "$$0")" && pwd)
                |""".stripMargin
      for s <- services do
        sb ++= s"""railway up --service ${q(s.name)} --path-as-root "$$here/${s.name}"\n"""
      sb.result()

  // ---- shared -------------------------------------------------------

  /** JSON a person reads: two-space indent, one field per line */
  private def pretty(j: okay.codec.Json, depth: Int): String =
    import okay.codec.Json
    val pad = "  " * (depth + 1)
    j match
      case Json.JObj(Vector()) => "{}"
      case Json.JObj(fs) =>
        fs.map((k, v) => s"$pad${Json.print(Json.JStr(k))}: ${pretty(v, depth + 1)}")
          .mkString("{\n", ",\n", "\n" + "  " * depth + "}")
      case Json.JArr(Vector()) => "[]"
      case Json.JArr(vs) =>
        vs.map(v => pad + pretty(v, depth + 1)).mkString("[\n", ",\n", "\n" + "  " * depth + "]")
      case other => Json.print(other)

  /** a TOML basic string */
  private def str(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  /** a double-quoted YAML scalar — every value quoted, so "8080" and
   * "true" stay the strings they are */
  private def y(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  /** a single-quoted shell word */
  private def q(s: String): String = "'" + s.replace("'", "'\\''") + "'"
