package okay.deploy

import java.nio.file.Path

/**
 * The two targets that need no account, and so can be proven on the
 * machine writing them (specs/deployment.md, stage 0).
 *
 * Both are pure `Deployment => files`. Neither knows anything the
 * other does: a `Need.Database` is a container on a laptop and a
 * refusal on a rented host, and the difference between those answers
 * is the target's own opinion, not a flag in the model.
 */
object Targets:

  val all: Vector[Target] = Vector(Laptop, Host)

  def byName(n: String): Option[Target] = all.find(_.name == n)

  private def quote(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  /** the image a service built from this repository runs as; a
   * `Run.Image` service is already one */
  private def imageOf(d: Deployment, s: Service): String = s.run match
    case Run.Image(repo, tag) => s"$repo:$tag"
    case Run.Module(_, _, _, _) => s"${d.name}/${s.name}:local"

  // ---- laptop: one compose file ------------------------------------

  /**
   * A laptop, through compose: every service a container, every need
   * beside it. What an operator gets is one file they could have
   * written by hand and can read without knowing this module exists
   * — which is the test of a renderer.
   */
  object Laptop extends Target:
    val name = "laptop"

    // `docker compose` is a PLUGIN and is missing on machines that
    // have docker (a distro's docker.io without the plugin package):
    // asking for it by name is the difference between a report and a
    // `docker: 'compose' is not a docker command` half way through
    def requires(d: Deployment): Vector[String] = Vector("docker", "docker compose")

    def up(dir: Path): Vector[String] = Vector("docker", "compose", "-f", dir.resolve("compose.yaml").toString, "up", "-d")
    def down(dir: Path): Vector[String] = Vector("docker", "compose", "-f", dir.resolve("compose.yaml").toString, "down")

    def render(d: Deployment): Either[String, Vector[(String, String)]] =
      d.ordered.map { services =>
        val sb = new StringBuilder
        sb ++= s"# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file\n"
        sb ++= "services:\n"
        val volumes = scala.collection.mutable.LinkedHashSet.empty[String]

        for s <- services do
          sb ++= s"  ${s.name}:\n"
          s.run match
            case Run.Image(repo, tag) => sb ++= s"    image: $repo:$tag\n"
            case Run.Module(_, moduleDir, _, _) =>
              sb ++= s"    image: ${imageOf(d, s)}\n"
              sb ++= "    build:\n      context: ../..\n"
              sb ++= s"      dockerfile: $moduleDir/deploy/Dockerfile\n"
          if s.ports.nonEmpty then
            sb ++= "    ports:\n"
            for p <- s.ports if p.public do sb ++= s"""      - "${p.number}:${p.number}"\n"""
          val env = s.settings.env ++ databaseEnv(s)
          if env.nonEmpty || s.secrets.nonEmpty then
            sb ++= "    environment:\n"
            for (k, v) <- env do sb ++= s"      $k: ${quote(v)}\n"
            // a secret is a REFERENCE: compose passes the variable
            // through from the operator's own environment, and no
            // value is ever written into this file
            for sec <- s.secrets; v <- envVarOf(sec) do sb ++= s"      $v: $${$v:?set $v in your environment or .env}\n"
          if s.volumes.nonEmpty then
            sb ++= "    volumes:\n"
            for v <- s.volumes do
              volumes += s"${s.name}-${v.name}"
              sb ++= s"      - ${s.name}-${v.name}:${v.path}\n"
          val deps = s.neighbours ++ s.databases.map(db => s"${s.name}-${db.as}") ++ s.caches.map(c => s"${s.name}-${c.as}")
          if deps.nonEmpty then
            sb ++= "    depends_on:\n"
            for dep <- deps do sb ++= s"      - $dep\n"
          s.mainPort.foreach { port =>
            sb ++= "    healthcheck:\n"
            sb ++= s"""      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:$port${s.health.livenessPath} || exit 1"]\n"""
            sb ++= "      interval: 10s\n      retries: 5\n"
            sb ++= s"      start_period: ${s.health.startupSeconds}s\n"
          }
          sb ++= "    restart: unless-stopped\n"

          // the needs that are containers of their own
          for db <- s.databases do
            val n = s"${s.name}-${db.as}"
            volumes += s"$n-data"
            sb ++= s"  $n:\n    image: ${db.engine.image(db.version)}\n"
            sb ++= "    environment:\n"
            for (k, v) <- databaseImageEnv(db) do sb ++= s"      $k: ${quote(v)}\n"
            sb ++= s"    volumes:\n      - $n-data:${dataDirOf(db.engine)}\n"
            sb ++= "    restart: unless-stopped\n"
          for c <- s.caches do
            sb ++= s"  ${s.name}-${c.as}:\n    image: ${c.engine.image(c.version)}\n    restart: unless-stopped\n"

        if volumes.nonEmpty then
          sb ++= "\nvolumes:\n"
          for v <- volumes do sb ++= s"  $v:\n"

        val envExample =
          "# every secret this deployment reads, by the name it is read under.\n" +
          "# Values go HERE or in your own environment — never in a rendered file.\n" +
          d.services.flatMap(s => s.secrets.flatMap(envVarOf).map(v => s"$v=\n")).distinct.mkString

        Vector("compose.yaml" -> sb.result()) ++
          (if envExample.linesIterator.exists(!_.startsWith("#")) then Vector(".env.example" -> envExample) else Vector.empty) ++
          d.extra.filter(_.target == name).map(e => e.path -> e.content)
      }

  // ---- host: systemd units -----------------------------------------

  /**
   * A rented server, through systemd: a unit per service, its
   * settings in an `EnvironmentFile`, and an install script that puts
   * both where systemd looks.
   *
   * A `Need.Database` REFUSES here, by name, and that refusal is the
   * point rather than a gap: installing and running a Postgres on
   * someone's server is not a thing a deployment renderer should do
   * quietly, and a unit that assumed a database was already there
   * would fail at 3am instead. The operator points the service at a
   * database they run, through a setting.
   */
  object Host extends Target:
    val name = "host"

    def requires(d: Deployment): Vector[String] = Vector("systemctl", "java")

    def up(dir: Path): Vector[String] = Vector("sh", dir.resolve("install.sh").toString)
    def down(dir: Path): Vector[String] = Vector("sh", dir.resolve("uninstall.sh").toString)

    def render(d: Deployment): Either[String, Vector[(String, String)]] =
      val unsupported = d.services.flatMap { s =>
        s.databases.map(db => s"${s.name} needs a ${db.engine} and the host target does not install one") ++
          s.caches.map(c => s"${s.name} needs a ${c.engine} and the host target does not install one")
      }
      if unsupported.nonEmpty then
        Left(unsupported.mkString("; ") +
          " — point the service at one you run, through a setting, or use the laptop/cluster target")
      else d.ordered.map { services =>
        val units = services.map { s =>
          val exec = s.run match
            case Run.Module(_, _, mainClass, javaOpts) =>
              val opts = if javaOpts.isBlank then "" else javaOpts.trim + " "
              s"/usr/bin/env java $opts-cp /opt/${d.name}/${s.name}/app.jar $mainClass"
            case Run.Image(repo, tag) =>
              s"/usr/bin/env docker run --rm --name ${s.name} $repo:$tag"
          val after = s.neighbours.map(n => s"$n.service").mkString(" ")
          s"${s.name}.service" ->
            s"""# generated by okay-deploy from ${d.name}'s Deployment value — edit the value, not this file
               |[Unit]
               |Description=${d.name} / ${s.name}
               |After=network-online.target${if after.isEmpty then "" else " " + after}
               |Wants=network-online.target${if after.isEmpty then "" else " " + after}
               |
               |[Service]
               |Type=simple
               |User=${d.name}
               |Group=${d.name}
               |WorkingDirectory=/opt/${d.name}/${s.name}
               |EnvironmentFile=/etc/${d.name}/${s.name}.env
               |ExecStart=$exec
               |Restart=on-failure
               |RestartSec=5
               |TimeoutStartSec=${s.health.startupSeconds}
               |# what a service can reach, narrowed to what it needs
               |NoNewPrivileges=true
               |PrivateTmp=true
               |ProtectSystem=strict
               |ProtectHome=true
               |ReadWritePaths=${(s.volumes.map(_.path) :+ s"/var/lib/${d.name}/${s.name}").mkString(" ")}
               |
               |[Install]
               |WantedBy=multi-user.target
               |""".stripMargin
        }

        val envFiles = services.map { s =>
          s"${s.name}.env" ->
            (s"# generated by okay-deploy. Settings live here; SECRETS are referenced,\n" +
             s"# never written — add their values to this file yourself, 0600, root-owned.\n" +
             s.settings.env.map((k, v) => s"$k=$v\n").mkString +
             s.secrets.flatMap(envVarOf).map(v => s"# $v=            # required: ${v}\n").mkString)
        }

        val install =
          s"""#!/bin/sh
             |# generated by okay-deploy from ${d.name}'s Deployment value.
             |# Read it before you run it: it creates a user, installs units and starts them.
             |set -eu
             |
             |command -v systemctl >/dev/null || { echo "this host has no systemd; okay-deploy's host target needs one" >&2; exit 3; }
             |command -v java >/dev/null || { echo "java is not installed. On Debian/Ubuntu: sudo apt-get install -y default-jre-headless" >&2; exit 3; }
             |
             |id ${d.name} >/dev/null 2>&1 || useradd --system --home /opt/${d.name} --shell /usr/sbin/nologin ${d.name}
             |install -d -o ${d.name} -g ${d.name} /opt/${d.name} /var/lib/${d.name} /etc/${d.name}
             |${services.map(s => s"install -d -o ${d.name} -g ${d.name} /opt/${d.name}/${s.name} /var/lib/${d.name}/${s.name}").mkString("\n")}
             |# a Need.Volume names the path the SERVICE sees; with no container
             |# in the way, that path is a directory on this host and the install
             |# makes it, owned by the service's own user
             |${services.flatMap(s => s.volumes.map(v => s"install -d -o ${d.name} -g ${d.name} ${v.path}")).mkString("\n")}
             |
             |for f in *.env; do
             |  [ -f "/etc/${d.name}/$$f" ] || install -m 0600 -o root -g root "$$f" "/etc/${d.name}/$$f"
             |done
             |install -m 0644 *.service /etc/systemd/system/
             |systemctl daemon-reload
             |${services.map(s => s"systemctl enable --now ${s.name}.service").mkString("\n")}
             |
             |echo "installed. Settings are in /etc/${d.name}/, units in /etc/systemd/system/."
             |echo "Secrets are NOT installed: add their values to the env files, then: systemctl restart ${services.map(_.name + ".service").mkString(" ")}"
             |""".stripMargin

        val uninstall =
          s"""#!/bin/sh
             |# generated by okay-deploy. Stops and removes the units; leaves
             |# /etc/${d.name} and /var/lib/${d.name} alone -- your settings and
             |# your data are not this script's to delete.
             |set -eu
             |${services.map(s => s"systemctl disable --now ${s.name}.service || true").mkString("\n")}
             |${services.map(s => s"rm -f /etc/systemd/system/${s.name}.service").mkString("\n")}
             |systemctl daemon-reload
             |echo "removed. Settings in /etc/${d.name} and data in /var/lib/${d.name} were kept."
             |""".stripMargin

        units ++ envFiles ++ Vector("install.sh" -> install, "uninstall.sh" -> uninstall) ++
          d.extra.filter(_.target == name).map(e => e.path -> e.content)
      }

  // ---- shared pieces ------------------------------------------------

  /** the environment variable a secret reference is read under, when
   * it is one this model can wire: `env:NAME` is NAME. Any other
   * scheme resolves inside the process and needs no plumbing here. */
  private[deploy] def envVarOf(s: okay.conf.Secret): Option[String] =
    Option.when(s.ref.startsWith("env:"))(s.ref.drop(4)).filter(_.nonEmpty)

  /** what a service is told about the database beside it -- one URL,
   * built where the engine is known, so an application does not
   * assemble one from four settings */
  private def databaseEnv(s: Service): Vector[(String, String)] =
    s.databases.map { db =>
      val host = s"${s.name}-${db.as}"
      val url = db.engine match
        case Engine.Postgres => s"jdbc:postgresql://$host:${db.engine.port}/${db.database}"
        case Engine.Mongo => s"mongodb://$host:${db.engine.port}/${db.database}"
        case other => s"$host:${other.port}"
      Settings.envName("", s"${db.as}_url") -> url
    } ++ s.caches.map(c => Settings.envName("", s"${c.as}_url") -> s"${s.name}-${c.as}:${c.engine.port}")

  private def databaseImageEnv(db: Need.Database): Vector[(String, String)] = db.engine match
    case Engine.Postgres => Vector(
      "POSTGRES_DB" -> db.database,
      "POSTGRES_USER" -> db.as,
      // a laptop's database is not a production one and does not
      // pretend to be: the password is fixed, said out loud, and the
      // cluster target will not do this
      "POSTGRES_PASSWORD" -> "local-only")
    case Engine.Mongo => Vector("MONGO_INITDB_DATABASE" -> db.database)
    case _ => Vector.empty

  private def dataDirOf(e: Engine): String = e match
    case Engine.Postgres => "/var/lib/postgresql/data"
    case Engine.Mongo => "/data/db"
    case Engine.Redis => "/data"
    case Engine.Kafka => "/bitnami/kafka"
