package okay.r.golden

import okay.!
import okay.codec.Schema
import okay.r.{Condition, R, REval, ToR}

/** Generated by okay.r.RFacade from `rfacadedemo`: regenerate it, do not edit it. */
object RFacadeDemo:

  /**
   * R: `scale2(x, by)`
   */
  def scale2[Out: Schema, A1: ToR, A2: ToR](x: A1, by: A2): Either[Condition, Out] ! REval =
    R.fn[Out]("rfacadedemo::scale2")(x, by)

  /**
   * R: `t.like(x)`
   */
  def t_like[Out: Schema, A1: ToR](x: A1): Either[Condition, Out] ! REval =
    R.fn[Out]("rfacadedemo::t.like")(x)

  /**
   * R: `trimmed(xs, trim)`
   * Left out, having defaults: trim.
   */
  def trimmed[Out: Schema, A1: ToR](xs: A1): Either[Condition, Out] ! REval =
    R.fn[Out]("rfacadedemo::trimmed")(xs)
